In [24]:
%load_ext autotime
import geopandas as gpd
import pandas as pd
from pathlib import Path
import folium
import os
import getpass
pd.set_option('display.max_columns', None)

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 0 ns (started: 2026-08-06 15:18:17 +12:00)

In [25]:
#This is where you edit the shoreline search parameters. The code below will find all shoreline shapefiles that match the search criteria, and then you can select which ones to process in the next step.
# See part 6 in Getting Started.ipynb for more details on how to use this notebook.
#
# BEFORE YOU RUN:
#  - pull the latest shared updates first:
#      git pull origin nzccdv2
#  - if you want to save your work online, do this in the terminal:
#      git add .
#      git commit -m "describe your changes"
#      git push origin yourname
#  - if Git reports a merge conflict, stop and ask for help before continuing
#  - confirm the shoreline files, baselines, and AOI polygons already exist in the expected Z: paths
#  - confirm the settings below match across all three notebooks
#
#  1) Find shoreline shapefiles using one of five modes:
# Select the seearch mode and set the cutoff date, target AOI, or target region as needed. The modes are:
#    - "date"                 : all AOIs modified after cutoff_date
#    - "aoi"                  : target AOI regardless of modified date
#    - "aoi_in_date_range"    : target AOI modified after cutoff_date
#    - "region"               : all AOIs in target region regardless of modified date
#    - "region_in_date_range" : all AOIs in target region modified after cutoff_date
#
# The cutoff can be either a single date (e.g. "2024-07-18") or a date range as a
# two-item tuple/list (e.g. ("2024-07-18", "2024-08-18")).
cutoff_date = ("2024-07-18")
search_roots = [Path(r"Z:\MaxarImagery\HighFreq"), Path(r"Z:\Retrolens")]
search_mode = "date"  # "date", "aoi", "aoi_in_date_range", "region", or "region_in_date_range"
target_aoi = "BrownsBay"  # used for "aoi" and "aoi_in_date_range"  # or use ["BrownsBay", "Omaha"] for multiple AOIs
target_region = "Auckland"  # used for "region" and "region_in_date_range"  # or use ["Auckland", "Northland"] for multiple regions

# Put your own name here. All three notebooks must use the same value, so your outputs
# stay in your own folder and can never overwrite someone else's run of the same area.
# For multiple AOIs or regions, use a Python list/tuple such as ["BrownsBay", "Omaha"] or ("Auckland", "Northland").
RUN_OWNER = "catriona"  # change this to your own name
if str(RUN_OWNER).strip().lower() in {"yourname", "changeme", "placeholder"}:
    print("WARNING: RUN_OWNER is still the placeholder value. Using your environment username as a default so outputs do not overwrite others.")
    RUN_OWNER = os.getenv("USERNAME") or getpass.getuser() or RUN_OWNER
DATA_DIR = Path("DataUpdatev2") / RUN_OWNER
DATA_DIR.mkdir(parents=True, exist_ok=True)

def _norm(s):
    return "".join(ch for ch in str(s).lower() if ch.isalnum())


def _as_target_list(value):
    if value is None:
        return []
    if isinstance(value, (list, tuple, set)):
        values = [str(v).strip() for v in value if str(v).strip()]
    else:
        values = [str(value).strip()]
    return [v for v in values if v]


def _coerce_cutoff_bounds(cutoff):
    if cutoff is None:
        raise ValueError("cutoff_date must not be None")

    if isinstance(cutoff, (tuple, list)):
        if len(cutoff) != 2:
            raise ValueError("cutoff_date range must be a two-item tuple/list")
        start = pd.Timestamp(cutoff[0]).normalize()
        end = pd.Timestamp(cutoff[1]).normalize()
        if start > end:
            start, end = end, start
        return start, end

    single = pd.Timestamp(cutoff).normalize()
    return single, None


def _matches_date(modified, cutoff_start, cutoff_end):
    if cutoff_end is None:
        return modified > cutoff_start
    return (modified >= cutoff_start) and (modified <= cutoff_end)


valid_modes = {"date", "aoi", "aoi_in_date_range", "region", "region_in_date_range"}
if search_mode not in valid_modes:
    raise ValueError(f"search_mode must be one of {sorted(valid_modes)}")

target_aoi_values = _as_target_list(target_aoi)
target_region_values = _as_target_list(target_region)
if search_mode in {"aoi", "aoi_in_date_range"} and not target_aoi_values:
    raise ValueError("target_aoi must be set when using AOI-based modes")
if search_mode in {"region", "region_in_date_range"} and not target_region_values:
    raise ValueError("target_region must be set when using region-based modes")

target_aoi_norms = {_norm(v) for v in target_aoi_values}
target_region_norms = {_norm(v) for v in target_region_values}
target_aoi_norm = _norm(target_aoi_values[0]) if target_aoi_values else ""
target_region_norm = _norm(target_region_values[0]) if target_region_values else ""
cutoff_start, cutoff_end = _coerce_cutoff_bounds(cutoff_date)
records = []

for root in search_roots:
    if not root.exists():
        continue

    # Search same directory layout and subfolders for shoreline shapefiles.
    for shp in root.glob("**/Shorelines/*.shp"):
        # Ignore shoreline files explicitly marked as AOI errors.
        if shp.stem.lower().startswith("[aoierr]"):
            continue

        # Expected layout: source_root / region / aoi / Shorelines / aoi_date.shp
        if len(shp.parts) < 5 or shp.parts[-2].lower() != "shorelines":
            continue

        region = shp.parts[-4]
        aoi = shp.parts[-3]
        modified = pd.Timestamp(shp.stat().st_mtime, unit="s")
        stem_aoi = shp.stem.rsplit("_", 1)[0]

        matches_aoi = bool(target_aoi_norms & {_norm(aoi), _norm(stem_aoi)})
        matches_region = bool(target_region_norms & {_norm(region)})
        matches_date = _matches_date(modified, cutoff_start, cutoff_end)

        include = False
        if search_mode == "date":
            include = matches_date
        elif search_mode == "aoi":
            include = matches_aoi
        elif search_mode == "aoi_in_date_range":
            include = matches_aoi and matches_date
        elif search_mode == "region":
            include = matches_region
        elif search_mode == "region_in_date_range":
            include = matches_region and matches_date

        if not include:
            continue

        records.append(
            {
                "source_root": str(root),
                "region": region,
                "aoi": aoi,
                "shoreline_path": str(shp),
                "modified": modified,
            }
        )

new_shorelines = pd.DataFrame(
    records,
    columns=["source_root", "region", "aoi", "shoreline_path", "modified"],
)
if not new_shorelines.empty:
    new_shorelines = new_shorelines.sort_values(["region", "aoi", "modified"]).reset_index(drop=True)


def _cutoff_label(cutoff_start, cutoff_end):
    if cutoff_end is None:
        return f"modified > {cutoff_start.date()}"
    return f"modified between {cutoff_start.date()} and {cutoff_end.date()}"


mode_label = {
    "date": f"Date range ({_cutoff_label(cutoff_start, cutoff_end)})",
    "aoi": f"AOI only ({target_aoi})",
    "aoi_in_date_range": f"AOI in date range ({target_aoi}; {_cutoff_label(cutoff_start, cutoff_end)})",
    "region": f"Region only ({target_region})",
    "region_in_date_range": f"Region in date range ({target_region}; {_cutoff_label(cutoff_start, cutoff_end)})",
}[search_mode]

print(f"Mode: {mode_label} | Matches: {len(new_shorelines)}")
new_shorelines

Mode: Date range (modified > 2024-07-18) | Matches: 181

,source_root,region,aoi,shoreline_path,modified
0,Z:\Retrolens,Auckland,Hobsonville,Z:\Retrolens\Auckland\Hobsonville\Shorelines\H...,2026-08-05 22:49:58.488281488
1,Z:\MaxarImagery\HighFreq,Auckland,KarekareBethells,Z:\MaxarImagery\HighFreq\Auckland\KarekareBeth...,2026-07-30 05:13:29.477445602
2,Z:\MaxarImagery\HighFreq,Auckland,KarekareBethells,Z:\MaxarImagery\HighFreq\Auckland\KarekareBeth...,2026-07-30 05:13:29.679181576
3,Z:\Retrolens,Auckland,ManukapuaIsland,Z:\Retrolens\Auckland\ManukapuaIsland\Shorelin...,2025-06-16 01:42:47.641532183
4,Z:\Retrolens,Auckland,ManukapuaIsland,Z:\Retrolens\Auckland\ManukapuaIsland\Shorelin...,2025-10-23 23:45:07.069980383
...,...,...,...,...,...
176,Z:\MaxarImagery\HighFreq,Wellington,TeHoroBeach,Z:\MaxarImagery\HighFreq\Wellington\TeHoroBeac...,2025-12-09 01:55:56.380937815
177,Z:\MaxarImagery\HighFreq,Wellington,TeHoroBeach,Z:\MaxarImagery\HighFreq\Wellington\TeHoroBeac...,2025-12-09 01:57:07.187499762
178,Z:\MaxarImagery\HighFreq,Wellington,TeHoroBeach,Z:\MaxarImagery\HighFreq\Wellington\TeHoroBeac...,2025-12-09 01:58:12.399565697
179,Z:\MaxarImagery\HighFreq,WestCoast,GreymouthSouth,Z:\MaxarImagery\HighFreq\WestCoast\GreymouthSo...,2025-12-08 01:17:36.517990588
180,Z:\MaxarImagery\HighFreq,WestCoast,GreymouthSouth,Z:\MaxarImagery\HighFreq\WestCoast\GreymouthSo...,2025-12-08 01:56:55.122789860

time: 5min 3s (started: 2026-08-06 15:18:17 +12:00)

In [26]:
# 2) Build unique AOI list and locate AOI polygons once per AOI
aoi_index = new_shorelines[["region", "aoi"]].drop_duplicates().reset_index(drop=True)
AOI_ROOT = Path(r"Z:\MaxarImagery\HighFreq\AOI")

def _norm_name(s):
    return "".join(ch for ch in str(s).lower() if ch.isalnum())

def _norm_tokens(s):
    # Preserve token order but drop punctuation/case differences.
    parts = []
    current = []
    for ch in str(s).lower():
        if ch.isalnum():
            current.append(ch)
        else:
            if current:
                parts.append("".join(current))
                current = []
    if current:
        parts.append("".join(current))
    return parts

def _aoi_name_variants(name):
    s = str(name)
    variants = [s]

    # Common cleanup: remove Beach suffix/token (e.g. MimiwhangataBeach -> Mimiwhangata).
    if s.lower().endswith("beach"):
        variants.append(s[:-5])
    variants.append(s.replace("Beach", ""))
    variants.append(s.replace("beach", ""))

    # Common swap for directional naming (e.g. OamaruNorth <-> NorthOamaru).
    if s.lower().startswith("north") and len(s) > 5:
        core = s[5:]
        variants.append(core + "North")
    if s.lower().startswith("south") and len(s) > 5:
        core = s[5:]
        variants.append(core + "South")
    if s.lower().endswith("north") and len(s) > 5:
        core = s[:-5]
        variants.append("North" + core)
    if s.lower().endswith("south") and len(s) > 5:
        core = s[:-5]
        variants.append("South" + core)

    # Deduplicate while preserving order and dropping empties.
    cleaned = []
    seen = set()
    for v in variants:
        v = v.strip()
        if not v:
            continue
        key = _norm_name(v)
        if key and key not in seen:
            seen.add(key)
            cleaned.append(v)
    return cleaned

def _match_score(left, right):
    from difflib import SequenceMatcher
    left_norm = _norm_name(left)
    right_norm = _norm_name(right)
    if left_norm == right_norm:
        return 1.0
    if left_norm in right_norm or right_norm in left_norm:
        return 0.98
    left_tokens = _norm_tokens(left)
    right_tokens = _norm_tokens(right)
    if left_tokens and right_tokens:
        left_join = "".join(left_tokens)
        right_join = "".join(right_tokens)
        if left_join == right_join:
            return 1.0
        if left_join in right_join or right_join in left_join:
            return 0.96
        if set(left_tokens) == set(right_tokens):
            return 0.95
    return SequenceMatcher(None, left_norm, right_norm).ratio()

def resolve_region_dir(region):
    if not AOI_ROOT.exists():
        return None

    direct = AOI_ROOT / str(region)
    if direct.exists():
        return direct

    target = _norm_name(region)
    dirs = [p for p in AOI_ROOT.iterdir() if p.is_dir()]

    # Prefer exact normalized match (e.g. "Bay of Plenty" -> "BayOfPlenty")
    for d in dirs:
        if _norm_name(d.name) == target:
            return d

    # Fallback: contains-based normalized match
    for d in dirs:
        dn = _norm_name(d.name)
        if target in dn or dn in target:
            return d

    return None

def resolve_aoi_path(region, aoi):
    aoi_dir = resolve_region_dir(region)
    if aoi_dir is None:
        return None

    variants = _aoi_name_variants(aoi)

    # Try direct naming conventions first for each variant.
    direct_candidates = []
    for v in variants:
        direct_candidates.extend([
            aoi_dir / f"{v}.shp",
            aoi_dir / f"{v}_AOI.shp",
        ])
    for p in direct_candidates:
        if p.exists():
            return p

    scored = []

    # Score all candidate shapefiles in the AOI folder.
    for p in aoi_dir.glob("*.shp"):
        stem = p.stem
        score = max(_match_score(v, stem) for v in variants)
        scored.append((score, p))

    if scored:
        best_score, best_path = max(scored, key=lambda item: item[0])

        # Accept very close name variants, or names where AOI is included in a longer stem.
        if best_score >= 0.82:
            return best_path

    # Rule: search one level deeper in AOI subfolders (e.g. Auckland/Kaipara Harbour/*.shp).
    subfolder_scored = []
    for p in aoi_dir.glob("*/*.shp"):
        folder_name = p.parent.name
        score_folder = max(_match_score(v, folder_name) for v in variants)
        score_file = max(_match_score(v, p.stem) for v in variants)
        score = max(score_folder, score_file)
        subfolder_scored.append((score, p))

    if subfolder_scored:
        best_score, best_path = max(subfolder_scored, key=lambda item: item[0])
        if best_score >= 0.82:
            return best_path

    # Last chance: if any variant is embedded in a longer stem with _AOI suffix.
    variant_norms = [_norm_name(v) for v in variants]
    for p in aoi_dir.glob("*_AOI.shp"):
        stem_norm = _norm_name(p.stem)
        if any(vn and vn in stem_norm for vn in variant_norms):
            return p

    return None

aoi_index["region_dir"] = aoi_index.region.map(resolve_region_dir)
aoi_index["region_dir"] = aoi_index.region_dir.map(lambda p: str(p) if p is not None else None)
aoi_index["aoi_path"] = aoi_index.apply(lambda r: resolve_aoi_path(r.region, r.aoi), axis=1)
aoi_index["aoi_exists"] = aoi_index.aoi_path.notna()
aoi_index["aoi_path"] = aoi_index.aoi_path.map(lambda p: str(p) if p is not None else None)
aoi_index

,region,aoi,region_dir,aoi_path,aoi_exists
0,Auckland,Hobsonville,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Hobsonvi...,True
1,Auckland,KarekareBethells,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Karekare...,True
2,Auckland,ManukapuaIsland,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
3,Auckland,MuriwaiSouth,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\MuriwaiS...,True
4,Auckland,Ngataringa,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Ngatarin...,True
5,Auckland,Omaha,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Omaha_AO...,True
6,Auckland,OmokoitiBay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
7,Auckland,OrongoPoint,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
8,Auckland,PollenIsland_shoreline,Z:\MaxarImagery\HighFreq\AOI\Auckland,NaN,False
9,Auckland,ShellyBeach,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
10,Auckland,ShoalBay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\ShoalBay...,True
11,Auckland,SoldiersBay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Soldiers...,True
12,Auckland,TeAtatu,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\TeAtatu_...,True
13,Auckland,TeHakono_clarksbay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
14,BayOfPlenty,Ohiwa,Z:\MaxarImagery\HighFreq\AOI\BayOfPlenty,Z:\MaxarImagery\HighFreq\AOI\BayOfPlenty\Ohiwa...,True
15,BayOfPlenty,OhopeBeach,Z:\MaxarImagery\HighFreq\AOI\BayOfPlenty,Z:\MaxarImagery\HighFreq\AOI\BayOfPlenty\Ohope...,True
16,BayOfPlenty,Waihi,Z:\MaxarImagery\HighFreq\AOI\BayOfPlenty,Z:\MaxarImagery\HighFreq\AOI\BayOfPlenty\Waihi...,True
17,Canterbury,GoochBay,Z:\MaxarImagery\HighFreq\AOI\Canterbury,Z:\MaxarImagery\HighFreq\AOI\Canterbury\GoochB...,True
18,Canterbury,Kaikoura,Z:\MaxarImagery\HighFreq\AOI\Canterbury,Z:\MaxarImagery\HighFreq\AOI\Canterbury\Kaikou...,True
19,Canterbury,SouthNewBrighton,Z:\MaxarImagery\HighFreq\AOI\Canterbury,Z:\MaxarImagery\HighFreq\AOI\Canterbury\SouthN...,True
20,Canterbury,Timaru,Z:\MaxarImagery\HighFreq\AOI\Canterbury,Z:\MaxarImagery\HighFreq\AOI\Canterbury\Pareor...,True
21,Gisborne,Gisborne,Z:\MaxarImagery\HighFreq\AOI\Gisborne,Z:\MaxarImagery\HighFreq\AOI\Gisborne\Gisborne...,True
22,Gisborne,Tolaga_KaiauaBay,Z:\MaxarImagery\HighFreq\AOI\Gisborne,Z:\MaxarImagery\HighFreq\AOI\Gisborne\Tolaga_K...,True
23,HawkesBay,CliftonHaumoana,Z:\MaxarImagery\HighFreq\AOI\HawkesBay,Z:\MaxarImagery\HighFreq\AOI\HawkesBay\Clifton...,True
24,HawkesBay,Mahanga,Z:\MaxarImagery\HighFreq\AOI\HawkesBay,Z:\MaxarImagery\HighFreq\AOI\HawkesBay\Mahanga...,True
25,HawkesBay,TableCape,Z:\MaxarImagery\HighFreq\AOI\HawkesBay,Z:\MaxarImagery\HighFreq\AOI\HawkesBay\TableCa...,True
26,HawkesBay,Waimarama,Z:\MaxarImagery\HighFreq\AOI\HawkesBay,Z:\MaxarImagery\HighFreq\AOI\HawkesBay\Waimara...,True
27,Manawatu-Whanganui,WhanganuiSouth,Z:\MaxarImagery\HighFreq\AOI\Manawatu-Whanganui,Z:\MaxarImagery\HighFreq\AOI\Manawatu-Whanganu...,True
28,Nelson,Nelson,Z:\MaxarImagery\HighFreq\AOI\Nelson,Z:\MaxarImagery\HighFreq\AOI\Nelson\Nelson_AOI...,True
29,Northland,FrenchmansBay,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Frenchm...,True
30,Northland,MarsdenPoint,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Marsden...,True
31,Northland,MataiBay,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\MataiBa...,True
32,Northland,Mimiwhangata,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Mimiwha...,True
33,Northland,Pataua,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Pataua_...,True
34,Northland,Pouto,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Pouto.shp,True
35,Northland,TaupiriBay,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Taupiri...,True
36,Northland,Tinopai,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Tinopai...,True
37,Northland,Waipu,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Waipu_A...,True
38,Otago,AllansBeach,Z:\MaxarImagery\HighFreq\AOI\Otago,Z:\MaxarImagery\HighFreq\AOI\Otago\AllansBeach...,True
39,Otago,Aramoana,Z:\MaxarImagery\HighFreq\AOI\Otago,Z:\MaxarImagery\HighFreq\AOI\Otago\Aramoana_AO...,True
40,Otago,StKilda_Tomahawk_SmaillsBeach,Z:\MaxarImagery\HighFreq\AOI\Otago,Z:\MaxarImagery\HighFreq\AOI\Otago\StKilda_Tom...,True
41,Otago,Waikouaiti,Z:\MaxarImagery\HighFreq\AOI\Otago,Z:\MaxarImagery\HighFreq\AOI\Otago\Waikouaiti_...,True
42,Otago,Warrington,Z:\MaxarImagery\HighFreq\AOI\Otago,Z:\MaxarImagery\HighFreq\AOI\Otago\Warrington_...,True
43,Southland,Riverton,Z:\MaxarImagery\HighFreq\AOI\Southland,Z:\MaxarImagery\HighFreq\AOI\Southland\Riverto...,True
44,Tasman,Mapua,Z:\MaxarImagery\HighFreq\AOI\Tasman,Z:\MaxarImagery\HighFreq\AOI\Tasman\Mapua_AOI.shp,True
45,Tasman,TakakaRiver_North,Z:\MaxarImagery\HighFreq\AOI\Tasman,Z:\MaxarImagery\HighFreq\AOI\Tasman\TakakaRive...,True
46,Waikato,Mokau,Z:\MaxarImagery\HighFreq\AOI\Waikato,Z:\MaxarImagery\HighFreq\AOI\Waikato\Mokau_AOI...,True
47,Waikato,Pauanui_Tairua,Z:\MaxarImagery\HighFreq\AOI\Waikato,Z:\MaxarImagery\HighFreq\AOI\Waikato\Pauanui_T...,True
48,Waikato,PortWaikato,Z:\MaxarImagery\HighFreq\AOI\Waikato,Z:\MaxarImagery\HighFreq\AOI\Waikato\PortWaika...,True
49,Waikato,Whitianga,Z:\MaxarImagery\HighFreq\AOI\Waikato,Z:\MaxarImagery\HighFreq\AOI\Waikato\Whitianga...,True
50,Wellington,KapitiMid,Z:\MaxarImagery\HighFreq\AOI\Wellington,Z:\MaxarImagery\HighFreq\AOI\Wellington\Kapiti...,True
51,Wellington,KapitiNorth,Z:\MaxarImagery\HighFreq\AOI\Wellington,Z:\MaxarImagery\HighFreq\AOI\Wellington\Kapiti...,True
52,Wellington,KapitiSouth,Z:\MaxarImagery\HighFreq\AOI\Wellington,Z:\MaxarImagery\HighFreq\AOI\Wellington\Kapiti...,True
53,Wellington,Otaki,Z:\MaxarImagery\HighFreq\AOI\Wellington,Z:\MaxarImagery\HighFreq\AOI\Wellington\Otaki_...,True
54,Wellington,Paekakariki,Z:\MaxarImagery\HighFreq\AOI\Wellington,NaN,False
55,Wellington,Paraparaumu,Z:\MaxarImagery\HighFreq\AOI\Wellington,NaN,False
56,Wellington,TeHoroBeach,Z:\MaxarImagery\HighFreq\AOI\Wellington,NaN,False
57,WestCoast,GreymouthSouth,Z:\MaxarImagery\HighFreq\AOI\WestCoast,Z:\MaxarImagery\HighFreq\AOI\WestCoast\Greymou...,True

time: 2.52 s (started: 2026-08-06 15:23:20 +12:00)

In [27]:
# 3) Load AOI polygons and baselines, then filter each baseline to its AOI polygon
aoi_index = aoi_index.copy()

# Safety fallback: rerun resolver in case any AOIs were still unresolved.
missing_mask = ~aoi_index.aoi_exists
if missing_mask.any():
    aoi_index.loc[missing_mask, "aoi_path"] = aoi_index.loc[missing_mask].apply(
        lambda r: resolve_aoi_path(r.region, r.aoi), axis=1
    )
    aoi_index["aoi_exists"] = aoi_index.aoi_path.notna()
    aoi_index["aoi_path"] = aoi_index.aoi_path.map(lambda p: str(p) if p is not None else None)

print("=" * 80)
print("TABLE 1: AOI POLYGONS NOT FOUND (cannot generate transects for these)")
print("=" * 80)
missing_aoi = aoi_index.loc[~aoi_index.aoi_exists].copy()
if not missing_aoi.empty:
    missing_aoi = missing_aoi.sort_values(["region", "aoi"]).reset_index(drop=True)
    display(missing_aoi[["region", "aoi", "aoi_path"]])
    print(f"Total missing: {len(missing_aoi)} AOIs\n")
else:
    print("None - all AOI polygons found!\n")

valid_aoi = aoi_index.loc[aoi_index.aoi_exists].copy()
if len(valid_aoi) == 0:
    raise ValueError("No AOI polygons available for preview or baseline loading.")

def _region_variants(region):
    s = str(region)
    variants = [s]
    variants.extend(s.replace("_", " ").replace("-", " ").split())
    if "-" in s:
        variants.append(s.split("-")[0])
    if " " in s:
        variants.append(s.split(" ")[0])

    cleaned = []
    seen = set()
    for v in variants:
        v = str(v).strip()
        if not v:
            continue
        key = _norm_name(v)
        if key and key not in seen:
            seen.add(key)
            cleaned.append(v)
    return cleaned

def _baseline_stem_core(stem):
    core = _norm_name(stem)
    for token in ["baselinemerge", "baseline", "merge"]:
        core = core.replace(token, "")
    return core

def resolve_baseline_path(region):
    """Fuzzy match region name to baseline shapefile."""
    baseline_dir = Path(r"Z:\DSAS\BaselineTemplate\Baselines")
    if not baseline_dir.exists():
        return None

    # Try exact match first.
    direct = baseline_dir / f"{region}_baseline.shp"
    if direct.exists():
        return direct

    # Accept any .shp containing baseline in stem (case-insensitive via normalization).
    baseline_files = [
        p for p in baseline_dir.glob("*.shp")
        if "baseline" in _norm_name(p.stem)
    ]
    if not baseline_files:
        return None

    region_vars = _region_variants(region)
    region_norms = [_norm_name(v) for v in region_vars]

    # First pass: contains/equality against cleaned baseline stem core.
    for bf in baseline_files:
        core = _baseline_stem_core(bf.stem)
        if any(rn == core or (rn and rn in core) or (core and core in rn) for rn in region_norms):
            return bf

    # Fallback: fuzzy score against both full stem and cleaned stem core.
    scored = []
    for bf in baseline_files:
        stem_norm = _norm_name(bf.stem)
        stem_core = _baseline_stem_core(bf.stem)
        score = max(
            max(_match_score(rn, stem_norm) for rn in region_norms),
            max(_match_score(rn, stem_core) for rn in region_norms),
        )
        scored.append((score, bf))

    if scored:
        best_score, best_path = max(scored, key=lambda item: item[0])
        if best_score >= 0.72:
            return best_path

    return None

baseline_rows = []
for row in valid_aoi.itertuples(index=False):
    aoi_gdf = gpd.read_file(row.aoi_path)
    aoi_geom = aoi_gdf.union_all()

    baseline_path = resolve_baseline_path(row.region)
    if baseline_path is None:
        continue

    baseline = gpd.read_file(baseline_path).to_crs(aoi_gdf.crs)
    baseline = baseline[baseline.intersects(aoi_geom)].copy()
    if baseline.empty:
        continue

    baseline["region"] = row.region
    baseline["aoi"] = row.aoi
    baseline["aoi_path"] = row.aoi_path
    baseline["baseline_path"] = str(baseline_path)
    baseline_rows.append(baseline.to_crs(2193))

assert len(baseline_rows) > 0, "No baseline segments intersected AOI polygons"
baseline = gpd.GeoDataFrame(pd.concat(baseline_rows, ignore_index=True), crs=2193)

# Find which AOIs have polygons but NO baseline overlap
baseline_aois_with_coverage = baseline[["region", "aoi"]].drop_duplicates()
all_valid_aois = valid_aoi[["region", "aoi"]].copy()
no_baseline_mask = ~all_valid_aois.set_index(["region", "aoi"]).index.isin(
    baseline_aois_with_coverage.set_index(["region", "aoi"]).index
)
no_baseline_aois = all_valid_aois[no_baseline_mask].sort_values(["region", "aoi"]).reset_index(drop=True)

print("=" * 80)
print("TABLE 2: AOI POLYGONS FOUND BUT NO BASELINE OVERLAP (cannot generate transects)")
print("=" * 80)
if not no_baseline_aois.empty:
    print(f"Total found but no baseline: {len(no_baseline_aois)} AOIs\n")
    display(no_baseline_aois)
else:
    print("None - all found AOIs have baseline coverage!\n")

================================================================================
TABLE 1: AOI POLYGONS NOT FOUND (cannot generate transects for these)
================================================================================

       region                     aoi aoi_path
0    Auckland  PollenIsland_shoreline      nan
1  Wellington             Paekakariki      nan
2  Wellington             Paraparaumu      nan
3  Wellington             TeHoroBeach      nan

Total missing: 4 AOIs

================================================================================
TABLE 2: AOI POLYGONS FOUND BUT NO BASELINE OVERLAP (cannot generate transects)
================================================================================
Total found but no baseline: 2 AOIs

     region                 aoi
0  Auckland     ManukapuaIsland
1  Auckland  TeHakono_clarksbay

time: 13.3 s (started: 2026-08-06 15:23:23 +12:00)

In [28]:
# 4) Use one AOI polygon as bbox geometry for preview
valid_aoi = aoi_index[aoi_index.aoi_exists].copy()
if len(valid_aoi) == 0:
    raise ValueError("No AOI polygons available for preview.")

sample = valid_aoi.iloc[0]
bbox = gpd.read_file(sample.aoi_path).to_crs(2193)
aoi_shoreline_paths = new_shorelines.query("region == @sample.region and aoi == @sample.aoi").shoreline_path

shorelines_preview = []
for fp in aoi_shoreline_paths:
    g = gpd.read_file(fp).to_crs(2193)
    g["source_file"] = fp
    shorelines_preview.append(g)

if len(shorelines_preview) == 0:
    raise ValueError(f"No new shorelines for sample AOI {sample.region}/{sample.aoi}")

shorelines_preview = gpd.GeoDataFrame(pd.concat(shorelines_preview, ignore_index=True), crs=2193)
baseline_preview = baseline[(baseline.region == sample.region) & (baseline.aoi == sample.aoi)].copy()

m = shorelines_preview.explore(name="new shorelines")
bbox.boundary.explore(m=m, color="blue", name="AOI polygon (bbox)")
baseline_preview.explore(m=m, color="red", name="baseline filtered to AOI")
folium.LayerControl(collapsed=False).add_to(m)
m

time: 266 ms (started: 2026-08-06 15:23:36 +12:00)

In [ ]:
# 5) Generate transects per AOI using AOI-filtered baseline segments from Cell 3
# Make this cell self-contained for imports if run standalone.
import geopandas as gpd
import pandas as pd
import numpy as np
from pathlib import Path
from tqdm.auto import tqdm
from shapely.geometry import LineString, Point
from shapely import line_locate_point
import folium


def create_transects(line, spacing=10, transect_length=400):
    transects = []
    distances = np.arange(0, line.length, spacing)

    for distance in distances:
        point = line.interpolate(distance)
        nearest_point_ahead = line.interpolate(min(distance + 1e-6, line.length))
        direction = np.arctan2(nearest_point_ahead.y - point.y, nearest_point_ahead.x - point.x)
        transect = LineString([
            Point(
                point.x - transect_length / 2 * np.cos(direction + np.pi / 2),
                point.y - transect_length / 2 * np.sin(direction + np.pi / 2)
            ),
            Point(
                point.x + transect_length / 2 * np.cos(direction + np.pi / 2),
                point.y + transect_length / 2 * np.sin(direction + np.pi / 2)
            )
        ])
        transects.append(transect)
    return transects

route_ids = {
    "NorthIsland": 100,
    "WaihekeIsland": 101,
    "MatakanaIsland": 102,
    "SouthIsland": 200,
    "JackettIsland": 201,
    "MoturoaRabbitIsland": 202,
    "Rakiura_StewartIsland": 203,
}


def _route_name_from_path(path_obj):
    stem = path_obj.stem
    if stem.lower().endswith("_route"):
        return stem[:-6]
    if stem.lower().endswith("route"):
        return stem[:-5].rstrip("_-")
    return stem


def load_routes_gdf():
    route_dirs = [
        Path(r"Z:\DSAS\BaselineTemplate\Routes"),
        Path("Data for testing/Routes"),
    ]

    route_frames = []
    for route_dir in route_dirs:
        if not route_dir.exists():
            continue

        for shp in route_dir.rglob("*.shp"):
            stem_norm = shp.stem.lower()
            if "route" not in stem_norm or "points" in stem_norm:
                continue

            g = gpd.read_file(shp)
            if g.empty:
                continue

            # Normalize route name so it always matches keys in route_ids.
            if "name" in g.columns and g["name"].notna().any():
                g["name"] = g["name"].fillna(_route_name_from_path(shp))
            else:
                g["name"] = _route_name_from_path(shp)

            route_frames.append(g.to_crs(2193))

    if len(route_frames) == 0:
        raise ValueError("No route shapefiles found. Check route paths.")

    return gpd.GeoDataFrame(pd.concat(route_frames, ignore_index=True), crs=2193)


existing_routes = globals().get("routes")
if existing_routes is None or len(existing_routes) == 0:
    routes = load_routes_gdf()
else:
    routes = existing_routes.to_crs(2193)

transect_frames = []
matched_routes = []

for _, row in tqdm(valid_aoi.iterrows(), total=len(valid_aoi)):
    region = row.region
    aoi = row.aoi
    aoi_geom = gpd.read_file(row.aoi_path).to_crs(2193).union_all()

    # Use baseline segments already filtered to this AOI in Cell 3.
    baseline_subset = baseline[(baseline.region == region) & (baseline.aoi == aoi)].copy()
    if len(baseline_subset) == 0:
        continue

    baseline_lines = baseline_subset.explode(index_parts=False).geometry
    baseline_lines = baseline_lines[baseline_lines.geom_type.isin(["LineString", "MultiLineString"])].explode(index_parts=False)
    if len(baseline_lines) == 0:
        continue

    # Pick the best matching route by maximum overlap length with AOI.
    route_subset = routes[routes.intersects(aoi_geom)].copy()
    if len(route_subset) == 0:
        print(f"No route found for {region}/{aoi}")
        continue

    route_subset["overlap_len"] = route_subset.geometry.intersection(aoi_geom).length
    route = route_subset.sort_values("overlap_len", ascending=False).iloc[0]
    route_name = str(route["name"]).strip()
    if route_name not in route_ids:
        print(f"Route name '{route_name}' missing in route_ids for {region}/{aoi}")
        continue
    code = route_ids[route_name]

    aoi_transects = []
    for line in baseline_lines:
        aoi_transects.extend(create_transects(line))
    if len(aoi_transects) == 0:
        continue

    aoi_transects = gpd.GeoDataFrame({
        "region": region,
        "aoi": aoi,
        "RouteName": route_name,
        "geometry": aoi_transects,
    }, crs=2193)

    meas = line_locate_point(route.geometry, aoi_transects.centroid)
    dist = (meas * 100).round().astype(int)
    aoi_transects["MEAS"] = meas
    aoi_transects["DIST"] = dist
    aoi_transects["Unique_ID"] = str(code) + aoi_transects["DIST"].astype(str).str.zfill(9)

    matched_routes.append({
        "region": region,
        "aoi": aoi,
        "route_name": route_name,
        "route_code": code,
        "transects": len(aoi_transects),
    })
    transect_frames.append(aoi_transects)

if len(transect_frames) == 0:
    raise ValueError("No transects generated for available AOIs.")

my_transects = gpd.GeoDataFrame(pd.concat(transect_frames, ignore_index=True), crs=2193)
matched_routes = pd.DataFrame(matched_routes)
display(matched_routes)
display(my_transects.head())

m = my_transects.explore(name="generated transects", color="orange")
folium.LayerControl(collapsed=False).add_to(m)
m

  0%|          | 0/54 [00:00<?, ?it/s]

Island code 

The first three numbers of the uniqueID indicates which island the point/rate/intersect is on.  

North Island 

Code 

South Island 

Code 

North Island 

100 

South Island 

200 

Waiheke Island 

101 

Jackett Island 

201 

Matakana Island 

102 

Moturoa Island 

202 

Rakiura Island 

203 


For each island I created a Route shapefile and determined the start point. The distance along the route tool was used to calculate the distance from the start of the route for each point along the route. 

The last 9 digits of the Unique_ID are made up of the route distance output (6 digits) (MEAS distance) and any necessary leading zeros.  

The output of the distance along the route tool (MEAS) is multiplied by 100, converted to an integer, and saved as ‘DIST’ to ensure each value is unique.  

MEAS 

DIST 

Code 

Unique_ID 

2050.2952311 

205029 

201 

201000205029

In [ ]:
# QA 1: transect counts per Region/AOI
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

counts_by_aoi = (
    my_transects
    .groupby(["region", "aoi"])
    .size()
    .rename("transect_count")
    .reset_index()
    .sort_values(["region", "aoi"])
    .reset_index(drop=True)
)
counts_by_aoi

                region                            aoi  transect_count
0             Auckland                    OmokoitiBay             875
1             Auckland                    OrongoPoint             205
2             Auckland                    ShellyBeach             222
3          BayOfPlenty                          Ohiwa             482
4          BayOfPlenty                     OhopeBeach            1159
5          BayOfPlenty                          Waihi             860
6           Canterbury                       GoochBay             812
7           Canterbury                       Kaikoura            1200
8           Canterbury               SouthNewBrighton            1973
9           Canterbury                         Timaru            1340
10            Gisborne                       Gisborne            1359
11            Gisborne               Tolaga_KaiauaBay             799
12           HawkesBay                CliftonHaumoana             914
13           HawkesBay                        Mahanga             751
14           HawkesBay                      TableCape             392
15           HawkesBay                      Waimarama             551
16  Manawatu-Whanganui                 WhanganuiSouth             549
17              Nelson                         Nelson            1311
18           Northland                  FrenchmansBay             200
19           Northland                   MarsdenPoint             869
20           Northland                       MataiBay             300
21           Northland                   Mimiwhangata             344
22           Northland                         Pataua             473
23           Northland                          Pouto            2041
24           Northland                     TaupiriBay             778
25           Northland                        Tinopai             286
26           Northland                          Waipu            1356
27               Otago                    AllansBeach             354
28               Otago                       Aramoana             484
29               Otago  StKilda_Tomahawk_SmaillsBeach             474
30               Otago                     Waikouaiti             619
31               Otago                     Warrington             371
32           Southland                       Riverton             965
33              Tasman                          Mapua            2192
34              Tasman              TakakaRiver_North            1215
35             Waikato                          Mokau             410
36             Waikato                 Pauanui_Tairua             369
37             Waikato                    PortWaikato             352
38             Waikato                      Whitianga             332
39          Wellington                      KapitiMid            2111
40          Wellington                    KapitiNorth            1265
41          Wellington                    KapitiSouth            1266
42          Wellington                          Otaki            2010
43           WestCoast                 GreymouthSouth            1465

time: 0 ns (started: 2026-08-06 15:10:07 +12:00)

In [ ]:
# QA 2: duplicate Unique_ID checks
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

dup_ids = my_transects[my_transects.duplicated("Unique_ID", keep=False)].sort_values("Unique_ID")
print(f"Duplicate Unique_ID rows: {len(dup_ids)}")

dup_ids[["region", "aoi", "RouteName", "Unique_ID"]].head(20)

Duplicate Unique_ID rows: 5820

         region               aoi    RouteName     Unique_ID
30383   Waikato         Whitianga  NorthIsland  100302735671
30384   Waikato         Whitianga  NorthIsland  100302735671
10544  Gisborne  Tolaga_KaiauaBay  NorthIsland  100397547368
10648  Gisborne  Tolaga_KaiauaBay  NorthIsland  100397547368
10899  Gisborne  Tolaga_KaiauaBay  NorthIsland  100399032712
10897  Gisborne  Tolaga_KaiauaBay  NorthIsland  100399032712
10898  Gisborne  Tolaga_KaiauaBay  NorthIsland  100399032712
10900  Gisborne  Tolaga_KaiauaBay  NorthIsland  100399032712
10901  Gisborne  Tolaga_KaiauaBay  NorthIsland  100399032712
10903  Gisborne  Tolaga_KaiauaBay  NorthIsland  100399033052
10902  Gisborne  Tolaga_KaiauaBay  NorthIsland  100399033052
9996   Gisborne          Gisborne  NorthIsland  100406594285
9995   Gisborne          Gisborne  NorthIsland  100406594285
10001  Gisborne          Gisborne  NorthIsland  100406595139
10000  Gisborne          Gisborne  NorthIsland  100406595139
9998   Gisborne          Gisborne  NorthIsland  100406595139
9999   Gisborne          Gisborne  NorthIsland  100406595139
10003  Gisborne          Gisborne  NorthIsland  100406595962
10004  Gisborne          Gisborne  NorthIsland  100406595962
10005  Gisborne          Gisborne  NorthIsland  100406595962

time: 16 ms (started: 2026-08-06 15:10:07 +12:00)

In [ ]:
# QA 3: route code prefix used in generated Unique_ID
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

prefix_counts = (
    my_transects
    .assign(prefix=my_transects.Unique_ID.astype(str).str[:3])
    .groupby(["region", "aoi", "RouteName", "prefix"])
    .size()
    .rename("count")
    .reset_index()
    .sort_values(["region", "aoi", "RouteName", "prefix"])
    .reset_index(drop=True)
)
prefix_counts

,region,aoi,RouteName,prefix,count
0,Auckland,OmokoitiBay,NorthIsland,100,875
1,Auckland,OrongoPoint,NorthIsland,100,205
2,Auckland,ShellyBeach,NorthIsland,100,222
3,BayOfPlenty,Ohiwa,NorthIsland,100,482
4,BayOfPlenty,OhopeBeach,NorthIsland,100,1159
5,BayOfPlenty,Waihi,NorthIsland,100,860
6,Canterbury,GoochBay,SouthIsland,200,812
7,Canterbury,Kaikoura,SouthIsland,200,1200
8,Canterbury,SouthNewBrighton,SouthIsland,200,1973
9,Canterbury,Timaru,SouthIsland,200,1340
10,Gisborne,Gisborne,NorthIsland,100,1359
11,Gisborne,Tolaga_KaiauaBay,NorthIsland,100,799
12,HawkesBay,CliftonHaumoana,NorthIsland,100,914
13,HawkesBay,Mahanga,NorthIsland,100,751
14,HawkesBay,TableCape,NorthIsland,100,392
15,HawkesBay,Waimarama,NorthIsland,100,551
16,Manawatu-Whanganui,WhanganuiSouth,NorthIsland,100,549
17,Nelson,Nelson,SouthIsland,200,1311
18,Northland,FrenchmansBay,NorthIsland,100,200
19,Northland,MarsdenPoint,NorthIsland,100,869
20,Northland,MataiBay,NorthIsland,100,300
21,Northland,Mimiwhangata,NorthIsland,100,344
22,Northland,Pataua,NorthIsland,100,473
23,Northland,Pouto,NorthIsland,100,2041
24,Northland,TaupiriBay,NorthIsland,100,778
25,Northland,Tinopai,NorthIsland,100,286
26,Northland,Waipu,NorthIsland,100,1356
27,Otago,AllansBeach,SouthIsland,200,354
28,Otago,Aramoana,SouthIsland,200,484
29,Otago,StKilda_Tomahawk_SmaillsBeach,SouthIsland,200,474
30,Otago,Waikouaiti,SouthIsland,200,619
31,Otago,Warrington,SouthIsland,200,371
32,Southland,Riverton,SouthIsland,200,965
33,Tasman,Mapua,MoturoaRabbitIsland,202,2192
34,Tasman,TakakaRiver_North,SouthIsland,200,1215
35,Waikato,Mokau,NorthIsland,100,410
36,Waikato,Pauanui_Tairua,NorthIsland,100,369
37,Waikato,PortWaikato,NorthIsland,100,352
38,Waikato,Whitianga,NorthIsland,100,332
39,Wellington,KapitiMid,NorthIsland,100,2111
40,Wellington,KapitiNorth,NorthIsland,100,1265
41,Wellington,KapitiSouth,NorthIsland,100,1266
42,Wellington,Otaki,NorthIsland,100,2010
43,WestCoast,GreymouthSouth,SouthIsland,200,1465

time: 16 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
# QA 4: confirm required fields exist
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

required_cols = ["region", "aoi", "RouteName", "MEAS", "DIST", "Unique_ID", "geometry"]
missing_cols = [c for c in required_cols if c not in my_transects.columns]
assert len(missing_cols) == 0, f"Missing required columns: {missing_cols}"
print("OK - all required columns are present")

OK - all required columns are present
time: 15 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
# QA: MEAS distribution
my_transects.MEAS.describe()

count    3.865500e+04
mean     3.409626e+06
std      2.005502e+06
min      2.979506e+00
25%      1.775567e+06
50%      3.597853e+06
75%      4.943849e+06
max      7.258661e+06
Name: MEAS, dtype: float64

time: 16 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
# QA: DIST distribution
my_transects.DIST.describe()

count    3.865500e+04
mean     3.409626e+08
std      2.005502e+08
min      2.980000e+02
25%      1.775567e+08
50%      3.597853e+08
75%      4.943849e+08
max      7.258661e+08
Name: DIST, dtype: float64

time: 16 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
# QA: sample of generated IDs
my_transects.Unique_ID.astype(str).sort_values().head(20)

16823    100043811675
16824    100043812840
16825    100043813956
16826    100043815075
16827    100043816253
16828    100043817322
16829    100043818386
16830    100043819459
16831    100043820522
16832    100043821573
16833    100043822635
16834    100043823693
16835    100043824733
16836    100043825786
16837    100043826857
16838    100043827946
16839    100043829019
16840    100043830090
16841    100043831090
16842    100043832146
Name: Unique_ID, dtype: str

time: 15 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
# QA: duplicates per AOI
my_transects.groupby(["region", "aoi"]).apply(lambda g: g.Unique_ID.duplicated().sum()).rename("duplicate_id_count").reset_index()

                region                            aoi  duplicate_id_count
0             Auckland                    OmokoitiBay                  17
1             Auckland                    OrongoPoint                   6
2             Auckland                    ShellyBeach                  12
3          BayOfPlenty                          Ohiwa                   0
4          BayOfPlenty                     OhopeBeach                   0
5          BayOfPlenty                          Waihi                   0
6           Canterbury                       GoochBay                   0
7           Canterbury                       Kaikoura                   0
8           Canterbury               SouthNewBrighton                   0
9           Canterbury                         Timaru                   0
10            Gisborne                       Gisborne                  19
11            Gisborne               Tolaga_KaiauaBay                   6
12           HawkesBay                CliftonHaumoana                   0
13           HawkesBay                        Mahanga                   0
14           HawkesBay                      TableCape                   0
15           HawkesBay                      Waimarama                   0
16  Manawatu-Whanganui                 WhanganuiSouth                   0
17              Nelson                         Nelson                   2
18           Northland                  FrenchmansBay                   0
19           Northland                   MarsdenPoint                   0
20           Northland                       MataiBay                   0
21           Northland                   Mimiwhangata                   0
22           Northland                         Pataua                   0
23           Northland                          Pouto                 161
24           Northland                     TaupiriBay                   0
25           Northland                        Tinopai                   0
26           Northland                          Waipu                   0
27               Otago                    AllansBeach                   0
28               Otago                       Aramoana                   0
29               Otago  StKilda_Tomahawk_SmaillsBeach                   0
30               Otago                     Waikouaiti                   0
31               Otago                     Warrington                   3
32           Southland                       Riverton                   0
33              Tasman                          Mapua                1033
34              Tasman              TakakaRiver_North                   7
35             Waikato                          Mokau                   0
36             Waikato                 Pauanui_Tairua                   0
37             Waikato                    PortWaikato                   0
38             Waikato                      Whitianga                   1
39          Wellington                      KapitiMid                   4
40          Wellington                    KapitiNorth                   0
41          Wellington                    KapitiSouth                   0
42          Wellington                          Otaki                   0
43           WestCoast                 GreymouthSouth                   0

time: 16 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
# QA summary: PASS/FAIL checks for generated transects
qa_rows = []


def add_check(name, passed, detail=""):
    qa_rows.append({
        "check": name,
        "status": "PASS" if passed else "FAIL",
        "detail": str(detail),
    })


has_transects = "my_transects" in globals()
add_check("my_transects exists", has_transects, "Run Step 5 first" if not has_transects else f"rows={len(my_transects):,}")

if has_transects:
    add_check("non-empty transects", len(my_transects) > 0, f"rows={len(my_transects):,}")

    required_cols = ["region", "aoi", "RouteName", "MEAS", "DIST", "Unique_ID", "geometry"]
    missing_cols = [c for c in required_cols if c not in my_transects.columns]
    add_check("required columns present", len(missing_cols) == 0, "missing=" + ", ".join(missing_cols) if missing_cols else "all present")

    if len(missing_cols) == 0:
        null_geom = int(my_transects.geometry.isna().sum())
        add_check("geometry non-null", null_geom == 0, f"null_geometry={null_geom}")

        dup_uid = int(my_transects.duplicated("Unique_ID", keep=False).sum())
        add_check("no duplicate Unique_ID", dup_uid == 0, f"duplicate_rows={dup_uid}")

        dup_per_aoi = (
            my_transects
            .groupby(["region", "aoi"])
            .apply(lambda g: int(g.Unique_ID.duplicated().sum()))
            .rename("duplicate_id_count")
            .reset_index()
        )
        max_dup_per_aoi = int(dup_per_aoi["duplicate_id_count"].max()) if len(dup_per_aoi) > 0 else 0
        add_check("no duplicate Unique_ID within AOI", max_dup_per_aoi == 0, f"max_duplicate_per_aoi={max_dup_per_aoi}")

        meas_null = int(my_transects["MEAS"].isna().sum())
        dist_null = int(my_transects["DIST"].isna().sum())
        add_check("MEAS non-null", meas_null == 0, f"null_MEAS={meas_null}")
        add_check("DIST non-null", dist_null == 0, f"null_DIST={dist_null}")

        if dist_null == 0:
            dist_is_integer = bool((my_transects["DIST"] == my_transects["DIST"].round()).all())
            add_check("DIST integer-like", dist_is_integer, "all integer-like" if dist_is_integer else "non-integer DIST values found")

        uid_series = my_transects["Unique_ID"].astype(str)
        uid_format_ok = uid_series.str.match(r"^\d{12}$", na=False)
        bad_uid_count = int((~uid_format_ok).sum())
        add_check("Unique_ID format is 12 digits", bad_uid_count == 0, f"bad_format_rows={bad_uid_count}")

qa_summary = pd.DataFrame(qa_rows)

display(qa_summary)

fail_count = int((qa_summary["status"] == "FAIL").sum())
pass_count = int((qa_summary["status"] == "PASS").sum())
print(f"QA summary: {pass_count} PASS, {fail_count} FAIL")
if fail_count > 0:
    print("Review failed checks above.")
else:
    print("All QA checks passed.")

                               check status                      detail
0                my_transects exists   PASS                 rows=38,655
1                non-empty transects   PASS                 rows=38,655
2           required columns present   PASS                 all present
3                  geometry non-null   PASS             null_geometry=0
4             no duplicate Unique_ID   FAIL         duplicate_rows=5820
5  no duplicate Unique_ID within AOI   FAIL  max_duplicate_per_aoi=1033
6                      MEAS non-null   PASS                 null_MEAS=0
7                      DIST non-null   PASS                 null_DIST=0
8                  DIST integer-like   PASS            all integer-like
9      Unique_ID format is 12 digits   PASS           bad_format_rows=0

QA summary: 8 PASS, 2 FAIL
Review failed checks above.
time: 16 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
# Transect overview table
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

my_transects[["region", "aoi", "RouteName", "Unique_ID", "MEAS", "DIST", "geometry"]].head(20)

,region,aoi,RouteName,Unique_ID,MEAS,DIST,geometry
0,Auckland,OmokoitiBay,NorthIsland,100640347623,6.403476e+06,640347623,"LINESTRING (1708491.271 5966768.784, 1708406.3..."
1,Auckland,OmokoitiBay,NorthIsland,100640346987,6.403470e+06,640346987,"LINESTRING (1708501.051 5966770.914, 1708416.0..."
2,Auckland,OmokoitiBay,NorthIsland,100640346944,6.403469e+06,640346944,"LINESTRING (1708510.99 5966773.079, 1708425.69..."
3,Auckland,OmokoitiBay,NorthIsland,100640346264,6.403463e+06,640346264,"LINESTRING (1708520.584 5966775.168, 1708435.6..."
4,Auckland,OmokoitiBay,NorthIsland,100640346023,6.403460e+06,640346023,"LINESTRING (1708530.532 5966777.335, 1708445.2..."
5,Auckland,OmokoitiBay,NorthIsland,100640345615,6.403456e+06,640345615,"LINESTRING (1708540.135 5966779.426, 1708455.1..."
6,Auckland,OmokoitiBay,NorthIsland,100640345057,6.403451e+06,640345057,"LINESTRING (1708550.074 5966781.591, 1708464.7..."
7,Auckland,OmokoitiBay,NorthIsland,100641451225,6.414512e+06,641451225,"LINESTRING (1708559.667 5966783.68, 1708474.73..."
8,Auckland,OmokoitiBay,NorthIsland,100641452223,6.414522e+06,641452223,"LINESTRING (1708569.626 5966785.848, 1708484.3..."
9,Auckland,OmokoitiBay,NorthIsland,100641457943,6.414579e+06,641457943,"LINESTRING (1708579.397 5966787.976, 1708494.0..."
10,Auckland,OmokoitiBay,NorthIsland,100641458931,6.414589e+06,641458931,"LINESTRING (1708588.98 5966790.063, 1708504.04..."
11,Auckland,OmokoitiBay,NorthIsland,100641459918,6.414599e+06,641459918,"LINESTRING (1708598.929 5966792.23, 1708513.63..."
12,Auckland,OmokoitiBay,NorthIsland,100641460390,6.414604e+06,641460390,"LINESTRING (1708608.532 5966794.321, 1708523.5..."
13,Auckland,OmokoitiBay,NorthIsland,100641461137,6.414611e+06,641461137,"LINESTRING (1708618.471 5966796.486, 1708533.1..."
14,Auckland,OmokoitiBay,NorthIsland,100641462130,6.414621e+06,641462130,"LINESTRING (1708628.064 5966798.575, 1708543.1..."
15,Auckland,OmokoitiBay,NorthIsland,100641462517,6.414625e+06,641462517,"LINESTRING (1708638.023 5966800.744, 1708552.7..."
16,Auckland,OmokoitiBay,NorthIsland,100641463513,6.414635e+06,641463513,"LINESTRING (1708647.616 5966802.833, 1708562.6..."
17,Auckland,OmokoitiBay,NorthIsland,100641464509,6.414645e+06,641464509,"LINESTRING (1708657.377 5966804.959, 1708572.4..."
18,Auckland,OmokoitiBay,NorthIsland,100641465241,6.414652e+06,641465241,"LINESTRING (1708667.326 5966807.125, 1708582.0..."
19,Auckland,OmokoitiBay,NorthIsland,100641466238,6.414662e+06,641466238,"LINESTRING (1708676.929 5966809.217, 1708591.9..."

time: 0 ns (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
output_dir = DATA_DIR
output_dir.mkdir(parents=True, exist_ok=True)
my_transects.to_file(output_dir / "new_transects.shp")

time: 516 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
MHWL = gpd.read_file("Data for testing/lds-nz-coastline-mean-high-water-GPKG.zip!nz-coastline-mean-high-water.gpkg")
MHWL

,id,coast_category,publish_date,source,scale,length,geometry
0,35,None,2018,Topo Map Sheet CD17,50000,20668,"MULTILINESTRING ((1417590.036 4944127.623, 141..."
1,36,mangrove,2015,Topo Map Sheet AX31,50000,10798,"MULTILINESTRING ((1738929.442 6043210.165, 173..."
2,19,None,2014,Topo Map Sheet CJ08,50000,25146,"MULTILINESTRING ((1196402.666 4760219.876, 119..."
3,20,None,2016,Topo Map Sheet BP25,50000,49256,"MULTILINESTRING ((1601468.532 5452279.034, 160..."
4,21,None,2016,Topo Map Sheet CJ09,50000,41547,"MULTILINESTRING ((1223799.4 4770268.433, 12237..."
...,...,...,...,...,...,...,...
17764,17835,steep coast,2018,Topo Map Sheet BY24,50000,1496,"MULTILINESTRING ((1581612.377 5144055.548, 158..."
17765,17832,steep coast,2014,Topo Map Sheet AK01,50000,10110,"MULTILINESTRING ((1109557.769 4379877.965, 110..."
17766,17836,steep coast,2016,Topo Map Sheet BX24,50000,2065,"MULTILINESTRING ((1580939.969 5170478.415, 158..."
17767,17838,sandy shore,2018,Topo Map Sheet AW31,50000,4274,"MULTILINESTRING ((1736011.624 6054000.185, 173..."
17768,17839,sandy shore,2019,Topo Map Sheet BG43,50000,3618,"MULTILINESTRING ((2042256.483 5706728.184, 204..."

time: 328 ms (started: 2026-08-06 15:10:08 +12:00)

In [ ]:
intersects = gpd.GeoDataFrame({"Unique_ID": my_transects.Unique_ID, "geometry": my_transects.intersection(MHWL.union_all())}, crs=my_transects.crs)
intersects

          Unique_ID                         geometry
0      100640347623               LINESTRING Z EMPTY
1      100640346987               LINESTRING Z EMPTY
2      100640346944               LINESTRING Z EMPTY
3      100640346264               LINESTRING Z EMPTY
4      100640346023               LINESTRING Z EMPTY
...             ...                              ...
38650  200522978814  POINT (1451400.066 5299505.202)
38651  200522980273  POINT (1451404.082 5299514.355)
38652  200522986111  POINT (1451408.107 5299523.527)
38653  200522986592   POINT (1451412.124 5299532.68)
38654  200522986835  POINT (1451416.145 5299541.843)

[38655 rows x 2 columns]

time: 9.72 s (started: 2026-08-06 15:10:09 +12:00)

In [ ]:
intersects.loc[intersects.geom_type == "MultiPoint", "geometry"] = intersects.geometry[intersects.geom_type == "MultiPoint"].apply(lambda geom: list(geom.geoms)[-1])

time: 16 ms (started: 2026-08-06 15:10:18 +12:00)

In [ ]:
# Map preview in the same AOI area used in Step 4
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"
assert "baseline" in globals(), "Run Step 3 first to create baseline"
assert "new_shorelines" in globals(), "Run Step 1 first to create new_shorelines"

if "sample" not in globals() or sample is None:
    valid_preview = my_transects[["region", "aoi"]].drop_duplicates().reset_index(drop=True)
    if len(valid_preview) == 0:
        raise ValueError("No transects available for map preview")
    sample_region = valid_preview.iloc[0]["region"]
    sample_aoi = valid_preview.iloc[0]["aoi"]
else:
    sample_region = sample.region
    sample_aoi = sample.aoi

transects_preview = my_transects[(my_transects.region == sample_region) & (my_transects.aoi == sample_aoi)].copy()
if len(transects_preview) == 0:
    raise ValueError(f"No transects found for preview AOI {sample_region}/{sample_aoi}")

if "sample" in globals() and sample is not None and sample.region == sample_region and sample.aoi == sample_aoi:
    bbox_preview = bbox.copy()
else:
    aoi_path_preview = (
        valid_aoi
        .loc[(valid_aoi.region == sample_region) & (valid_aoi.aoi == sample_aoi), "aoi_path"]
        .iloc[0]
    )
    bbox_preview = gpd.read_file(aoi_path_preview).to_crs(2193)

baseline_preview = baseline[(baseline.region == sample_region) & (baseline.aoi == sample_aoi)].copy()
aoi_shoreline_paths = new_shorelines.query("region == @sample_region and aoi == @sample_aoi").shoreline_path

shorelines_preview = []
for fp in aoi_shoreline_paths:
    g = gpd.read_file(fp).to_crs(2193)
    shorelines_preview.append(g)

m = transects_preview.explore(name="generated transects", color="orange")
if len(shorelines_preview) > 0:
    gpd.GeoDataFrame(pd.concat(shorelines_preview, ignore_index=True), crs=2193).explore(m=m, name="new shorelines", color="black")
bbox_preview.boundary.explore(m=m, color="blue", name="AOI polygon (bbox)")
if len(baseline_preview) > 0:
    baseline_preview.explore(m=m, color="red", name="baseline filtered to AOI")
folium.LayerControl(collapsed=False).add_to(m)
print(f"Preview AOI: {sample_region}/{sample_aoi} | Transects shown: {len(transects_preview):,}")
m

ValueError: No transects found for preview AOI Auckland/ManukapuaIsland

time: 141 ms (started: 2026-08-06 15:10:18 +12:00)

In [ ]:
output_dir = DATA_DIR
output_dir.mkdir(parents=True, exist_ok=True)
intersects.to_file(output_dir / "new_points.shp")