In [31]:
%load_ext autotime
import geopandas as gpd
import pandas as pd
from pathlib import Path
import folium
import os
import getpass
pd.set_option('display.max_columns', None)

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 0 ns (started: 2026-08-18 16:23:23 +12:00)

In [32]:
#This is where you edit the shoreline search parameters. The code below will find all shoreline shapefiles that match the search criteria, and then you can select which ones to process in the next step.
# See part 6 in Getting Started.ipynb for more details on how to use this notebook.
#
# BEFORE YOU RUN:
#  - pull the latest shared updates first:
#      git pull origin nzccdv2
#  - if you want to save your work online, do this in the terminal:
#      git add .
#      git commit -m "describe your changes"
#      git push origin yourname
#  - if Git reports a merge conflict, stop and ask for help before continuing
#  - confirm the shoreline files, baselines, and AOI polygons already exist in the expected Z: paths
#  - confirm the settings below match across all three notebooks
#
#  1) Find shoreline shapefiles using one of five modes:
# Select the seearch mode and set the cutoff date, target AOI, or target region as needed. The modes are:
#    - "date"                 : all AOIs modified after cutoff_date
#    - "aoi"                  : target AOI regardless of modified date
#    - "aoi_in_date_range"    : target AOI modified after cutoff_date
#    - "region"               : all AOIs in target region regardless of modified date
#    - "region_in_date_range" : all AOIs in target region modified after cutoff_date
#
# The cutoff can be either a single date (e.g. "2024-07-18") or a date range as a
# two-item tuple/list (e.g. ("2024-07-18", "2024-08-18")).
cutoff_date = ("2024-07-18")
search_roots = [Path(r"Z:\MaxarImagery\HighFreq"), Path(r"Z:\Retrolens")]
search_mode = "aoi"  # "date", "aoi", "aoi_in_date_range", "region", or "region_in_date_range"
target_aoi = ["TeAtatu","Hobsonville","PollenIsland","ShoalBay","SoldiersBay","Ngataringa","FrenchmansBay","ManukapuaIsland","OmokoritoBay","OrongoPoint","Pouto","ShellyBeach","TeHakono_clarksBay","Tinopai"]  # used for "aoi" and "aoi_in_date_range"  # or use ["BrownsBay", "Omaha"] for multiple AOIs
target_region = "Auckland"  # used for "region" and "region_in_date_range"  # or use ["Auckland", "Northland"] for multiple regions

# Put your own name here. All three notebooks must use the same value, so your outputs
# stay in your own folder and can never overwrite someone else's run of the same area.
# For multiple AOIs or regions, use a Python list/tuple such as ["BrownsBay", "Omaha"] or ("Auckland", "Northland").
RUN_OWNER = "catriona"  # change this to your own name
if str(RUN_OWNER).strip().lower() in {"yourname", "changeme", "placeholder"}:
    print("WARNING: RUN_OWNER is still the placeholder value. Using your environment username as a default so outputs do not overwrite others.")
    RUN_OWNER = os.getenv("USERNAME") or getpass.getuser() or RUN_OWNER
DATA_DIR = Path("DataUpdatev2") / RUN_OWNER
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Run report: every skipped/missing item and summary table is collected here and written
# to new_transects.csv at the end. The "cell" column lets you tab/filter by the step that produced it.
RUN_REPORT_PATH = DATA_DIR / "new_transects.csv"
run_report_rows = []


def log_run_row(cell, category, status="MISSING", region=None, aoi=None, detail=""):
    run_report_rows.append({
        "cell": cell,
        "category": category,
        "status": status,
        "region": region,
        "aoi": aoi,
        "detail": str(detail),
    })


def clear_run_rows(cell):
    # Re-running a cell should replace its rows, not duplicate them.
    global run_report_rows
    run_report_rows = [r for r in run_report_rows if r["cell"] != cell]


def _norm(s):
    return "".join(ch for ch in str(s).lower() if ch.isalnum())


def _as_target_list(value):
    if value is None:
        return []
    if isinstance(value, (list, tuple, set)):
        values = [str(v).strip() for v in value if str(v).strip()]
    else:
        values = [str(value).strip()]
    return [v for v in values if v]


def _coerce_cutoff_bounds(cutoff):
    if cutoff is None:
        raise ValueError("cutoff_date must not be None")

    if isinstance(cutoff, (tuple, list)):
        if len(cutoff) != 2:
            raise ValueError("cutoff_date range must be a two-item tuple/list")
        start = pd.Timestamp(cutoff[0]).normalize()
        end = pd.Timestamp(cutoff[1]).normalize()
        if start > end:
            start, end = end, start
        return start, end

    single = pd.Timestamp(cutoff).normalize()
    return single, None


def _matches_date(modified, cutoff_start, cutoff_end):
    if cutoff_end is None:
        return modified > cutoff_start
    return (modified >= cutoff_start) and (modified <= cutoff_end)


valid_modes = {"date", "aoi", "aoi_in_date_range", "region", "region_in_date_range"}
if search_mode not in valid_modes:
    raise ValueError(f"search_mode must be one of {sorted(valid_modes)}")

target_aoi_values = _as_target_list(target_aoi)
target_region_values = _as_target_list(target_region)
if search_mode in {"aoi", "aoi_in_date_range"} and not target_aoi_values:
    raise ValueError("target_aoi must be set when using AOI-based modes")
if search_mode in {"region", "region_in_date_range"} and not target_region_values:
    raise ValueError("target_region must be set when using region-based modes")

target_aoi_norms = {_norm(v) for v in target_aoi_values}
target_region_norms = {_norm(v) for v in target_region_values}
target_aoi_norm = _norm(target_aoi_values[0]) if target_aoi_values else ""
target_region_norm = _norm(target_region_values[0]) if target_region_values else ""
cutoff_start, cutoff_end = _coerce_cutoff_bounds(cutoff_date)
records = []

for root in search_roots:
    if not root.exists():
        continue

    # Search same directory layout and subfolders for shoreline shapefiles.
    for shp in root.glob("**/Shorelines/*.shp"):
        # Ignore shoreline files explicitly marked as AOI errors.
        if shp.stem.lower().startswith("[aoierr]"):
            continue

        # Expected layout: source_root / region / aoi / Shorelines / aoi_date.shp
        if len(shp.parts) < 5 or shp.parts[-2].lower() != "shorelines":
            continue

        region = shp.parts[-4]
        aoi = shp.parts[-3]
        modified = pd.Timestamp(shp.stat().st_mtime, unit="s")
        stem_aoi = shp.stem.rsplit("_", 1)[0]

        matches_aoi = bool(target_aoi_norms & {_norm(aoi), _norm(stem_aoi)})
        matches_region = bool(target_region_norms & {_norm(region)})
        matches_date = _matches_date(modified, cutoff_start, cutoff_end)

        include = False
        if search_mode == "date":
            include = matches_date
        elif search_mode == "aoi":
            include = matches_aoi
        elif search_mode == "aoi_in_date_range":
            include = matches_aoi and matches_date
        elif search_mode == "region":
            include = matches_region
        elif search_mode == "region_in_date_range":
            include = matches_region and matches_date

        if not include:
            continue

        records.append(
            {
                "source_root": str(root),
                "region": region,
                "aoi": aoi,
                "shoreline_path": str(shp),
                "modified": modified,
            }
        )

new_shorelines = pd.DataFrame(
    records,
    columns=["source_root", "region", "aoi", "shoreline_path", "modified"],
)
if not new_shorelines.empty:
    new_shorelines = new_shorelines.sort_values(["region", "aoi", "modified"]).reset_index(drop=True)

clear_run_rows("Cell 1 - shoreline search")
if search_mode in {"aoi", "aoi_in_date_range"}:
    found_aoi_norms = {_norm(a) for a in new_shorelines.aoi.unique()} if not new_shorelines.empty else set()
    for requested in target_aoi_values:
        if _norm(requested) not in found_aoi_norms:
            log_run_row(
                "Cell 1 - shoreline search",
                "requested AOI has no matching shoreline files",
                aoi=requested,
                detail=f"search_mode={search_mode}",
            )


def _cutoff_label(cutoff_start, cutoff_end):
    if cutoff_end is None:
        return f"modified > {cutoff_start.date()}"
    return f"modified between {cutoff_start.date()} and {cutoff_end.date()}"


mode_label = {
    "date": f"Date range ({_cutoff_label(cutoff_start, cutoff_end)})",
    "aoi": f"AOI only ({target_aoi})",
    "aoi_in_date_range": f"AOI in date range ({target_aoi}; {_cutoff_label(cutoff_start, cutoff_end)})",
    "region": f"Region only ({target_region})",
    "region_in_date_range": f"Region in date range ({target_region}; {_cutoff_label(cutoff_start, cutoff_end)})",
}[search_mode]

print(f"Mode: {mode_label} | Matches: {len(new_shorelines)}")
new_shorelines

Mode: AOI only (['TeAtatu', 'Hobsonville', 'PollenIsland', 'ShoalBay', 'SoldiersBay', 'Ngataringa', 'FrenchmansBay', 'ManukapuaIsland', 'OmokoritoBay', 'OrongoPoint', 'Pouto', 'ShellyBeach', 'TeHakono_clarksBay', 'Tinopai']) | Matches: 67

,source_root,region,aoi,shoreline_path,modified
0,Z:\Retrolens,Auckland,Hobsonville,Z:\Retrolens\Auckland\Hobsonville\Shorelines\H...,2026-08-05 22:49:58.488281488
1,Z:\Retrolens,Auckland,ManukapuaIsland,Z:\Retrolens\Auckland\ManukapuaIsland\Shorelin...,2022-01-16 02:09:57.307988882
2,Z:\Retrolens,Auckland,ManukapuaIsland,Z:\Retrolens\Auckland\ManukapuaIsland\Shorelin...,2025-06-16 01:42:47.641532183
3,Z:\Retrolens,Auckland,ManukapuaIsland,Z:\Retrolens\Auckland\ManukapuaIsland\Shorelin...,2025-10-23 23:45:07.069980383
4,Z:\Retrolens,Auckland,ManukapuaIsland,Z:\Retrolens\Auckland\ManukapuaIsland\Shorelin...,2025-10-23 23:45:07.408631086
...,...,...,...,...,...
62,Z:\Retrolens,Northland,Tinopai,Z:\Retrolens\Northland\Tinopai\Shorelines\Tino...,2025-10-28 01:49:38.186976433
63,Z:\Retrolens,Northland,Tinopai,Z:\Retrolens\Northland\Tinopai\Shorelines\Tino...,2025-10-28 01:49:39.320811272
64,Z:\Retrolens,Northland,Tinopai,Z:\Retrolens\Northland\Tinopai\Shorelines\Tino...,2025-10-28 01:49:40.151776791
65,Z:\Retrolens,Northland,Tinopai,Z:\Retrolens\Northland\Tinopai\Shorelines\Tino...,2025-10-28 01:49:41.120065928
66,Z:\Retrolens,Northland,Tinopai,Z:\Retrolens\Northland\Tinopai\Shorelines\Tino...,2025-10-28 01:49:42.302623987

time: 3min 2s (started: 2026-08-18 16:23:23 +12:00)

In [33]:
# 2) Build unique AOI list and locate AOI polygons once per AOI
aoi_index = new_shorelines[["region", "aoi"]].drop_duplicates().reset_index(drop=True)
AOI_ROOT = Path(r"Z:\MaxarImagery\HighFreq\AOI")

def _norm_name(s):
    return "".join(ch for ch in str(s).lower() if ch.isalnum())

def _norm_tokens(s):
    # Preserve token order but drop punctuation/case differences.
    parts = []
    current = []
    for ch in str(s).lower():
        if ch.isalnum():
            current.append(ch)
        else:
            if current:
                parts.append("".join(current))
                current = []
    if current:
        parts.append("".join(current))
    return parts

def _aoi_name_variants(name):
    s = str(name)
    variants = [s]

    # Common cleanup: remove Beach suffix/token (e.g. MimiwhangataBeach -> Mimiwhangata).
    if s.lower().endswith("beach"):
        variants.append(s[:-5])
    variants.append(s.replace("Beach", ""))
    variants.append(s.replace("beach", ""))

    # Common swap for directional naming (e.g. OamaruNorth <-> NorthOamaru).
    if s.lower().startswith("north") and len(s) > 5:
        core = s[5:]
        variants.append(core + "North")
    if s.lower().startswith("south") and len(s) > 5:
        core = s[5:]
        variants.append(core + "South")
    if s.lower().endswith("north") and len(s) > 5:
        core = s[:-5]
        variants.append("North" + core)
    if s.lower().endswith("south") and len(s) > 5:
        core = s[:-5]
        variants.append("South" + core)

    # Deduplicate while preserving order and dropping empties.
    cleaned = []
    seen = set()
    for v in variants:
        v = v.strip()
        if not v:
            continue
        key = _norm_name(v)
        if key and key not in seen:
            seen.add(key)
            cleaned.append(v)
    return cleaned

def _match_score(left, right):
    from difflib import SequenceMatcher
    left_norm = _norm_name(left)
    right_norm = _norm_name(right)
    if left_norm == right_norm:
        return 1.0
    if left_norm in right_norm or right_norm in left_norm:
        return 0.98
    left_tokens = _norm_tokens(left)
    right_tokens = _norm_tokens(right)
    if left_tokens and right_tokens:
        left_join = "".join(left_tokens)
        right_join = "".join(right_tokens)
        if left_join == right_join:
            return 1.0
        if left_join in right_join or right_join in left_join:
            return 0.96
        if set(left_tokens) == set(right_tokens):
            return 0.95
    return SequenceMatcher(None, left_norm, right_norm).ratio()

def resolve_region_dir(region):
    if not AOI_ROOT.exists():
        return None

    direct = AOI_ROOT / str(region)
    if direct.exists():
        return direct

    target = _norm_name(region)
    dirs = [p for p in AOI_ROOT.iterdir() if p.is_dir()]

    # Prefer exact normalized match (e.g. "Bay of Plenty" -> "BayOfPlenty")
    for d in dirs:
        if _norm_name(d.name) == target:
            return d

    # Fallback: contains-based normalized match
    for d in dirs:
        dn = _norm_name(d.name)
        if target in dn or dn in target:
            return d

    return None

def resolve_aoi_path(region, aoi):
    aoi_dir = resolve_region_dir(region)
    if aoi_dir is None:
        return None

    variants = _aoi_name_variants(aoi)

    # Try direct naming conventions first for each variant.
    direct_candidates = []
    for v in variants:
        direct_candidates.extend([
            aoi_dir / f"{v}.shp",
            aoi_dir / f"{v}_AOI.shp",
        ])
    for p in direct_candidates:
        if p.exists():
            return p

    scored = []

    # Score all candidate shapefiles in the AOI folder.
    for p in aoi_dir.glob("*.shp"):
        stem = p.stem
        score = max(_match_score(v, stem) for v in variants)
        scored.append((score, p))

    if scored:
        best_score, best_path = max(scored, key=lambda item: item[0])

        # Accept very close name variants, or names where AOI is included in a longer stem.
        if best_score >= 0.82:
            return best_path

    # Rule: search one level deeper in AOI subfolders (e.g. Auckland/Kaipara Harbour/*.shp).
    subfolder_scored = []
    for p in aoi_dir.glob("*/*.shp"):
        folder_name = p.parent.name
        score_folder = max(_match_score(v, folder_name) for v in variants)
        score_file = max(_match_score(v, p.stem) for v in variants)
        score = max(score_folder, score_file)
        subfolder_scored.append((score, p))

    if subfolder_scored:
        best_score, best_path = max(subfolder_scored, key=lambda item: item[0])
        if best_score >= 0.82:
            return best_path

    # Last chance: if any variant is embedded in a longer stem with _AOI suffix.
    variant_norms = [_norm_name(v) for v in variants]
    for p in aoi_dir.glob("*_AOI.shp"):
        stem_norm = _norm_name(p.stem)
        if any(vn and vn in stem_norm for vn in variant_norms):
            return p

    return None

aoi_index["region_dir"] = aoi_index.region.map(resolve_region_dir)
aoi_index["region_dir"] = aoi_index.region_dir.map(lambda p: str(p) if p is not None else None)
aoi_index["aoi_path"] = aoi_index.apply(lambda r: resolve_aoi_path(r.region, r.aoi), axis=1)
aoi_index["aoi_exists"] = aoi_index.aoi_path.notna()
aoi_index["aoi_path"] = aoi_index.aoi_path.map(lambda p: str(p) if p is not None else None)
aoi_index

,region,aoi,region_dir,aoi_path,aoi_exists
0,Auckland,Hobsonville,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Hobsonvi...,True
1,Auckland,ManukapuaIsland,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
2,Auckland,Ngataringa,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Ngatarin...,True
3,Auckland,OmokoritoBay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
4,Auckland,OrongoPoint,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
5,Auckland,PollenIsland,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\PollenIs...,True
6,Auckland,ShellyBeach,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
7,Auckland,ShoalBay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\ShoalBay...,True
8,Auckland,SoldiersBay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Soldiers...,True
9,Auckland,TeAtatu,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\TeAtatu_...,True
10,Auckland,TeHakono_clarksbay,Z:\MaxarImagery\HighFreq\AOI\Auckland,Z:\MaxarImagery\HighFreq\AOI\Auckland\Kaipara ...,True
11,Northland,FrenchmansBay,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Frenchm...,True
12,Northland,Pouto,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Pouto.shp,True
13,Northland,Tinopai,Z:\MaxarImagery\HighFreq\AOI\Northland,Z:\MaxarImagery\HighFreq\AOI\Northland\Tinopai...,True

time: 891 ms (started: 2026-08-18 16:26:25 +12:00)

In [34]:
# 3) Load AOI polygons and baselines, then filter each baseline to its AOI polygon
aoi_index = aoi_index.copy()
clear_run_rows("Cell 3 - AOI polygons and baselines")

# Safety fallback: rerun resolver in case any AOIs were still unresolved.
missing_mask = ~aoi_index.aoi_exists
if missing_mask.any():
    aoi_index.loc[missing_mask, "aoi_path"] = aoi_index.loc[missing_mask].apply(
        lambda r: resolve_aoi_path(r.region, r.aoi), axis=1
    )
    aoi_index["aoi_exists"] = aoi_index.aoi_path.notna()
    aoi_index["aoi_path"] = aoi_index.aoi_path.map(lambda p: str(p) if p is not None else None)

print("=" * 80)
print("TABLE 1: AOI POLYGONS NOT FOUND (skipped, processing continues for other areas)")
print("=" * 80)
missing_aoi = aoi_index.loc[~aoi_index.aoi_exists].copy()
if not missing_aoi.empty:
    missing_aoi = missing_aoi.sort_values(["region", "aoi"]).reset_index(drop=True)
    display(missing_aoi[["region", "aoi", "aoi_path"]])
    print(f"Total missing: {len(missing_aoi)} AOIs\n")
    for row in missing_aoi.itertuples(index=False):
        log_run_row(
            "Cell 3 - AOI polygons and baselines",
            "AOI polygon not found",
            region=row.region,
            aoi=row.aoi,
            detail=f"searched under {AOI_ROOT}",
        )
else:
    print("None - all AOI polygons found!\n")

valid_aoi = aoi_index.loc[aoi_index.aoi_exists].copy()
if len(valid_aoi) == 0:
    print("WARNING: no AOI polygons resolved, so no baselines can be loaded. Later steps will be skipped.")

def _region_variants(region):
    s = str(region)
    variants = [s]
    variants.extend(s.replace("_", " ").replace("-", " ").split())
    if "-" in s:
        variants.append(s.split("-")[0])
    if " " in s:
        variants.append(s.split(" ")[0])

    cleaned = []
    seen = set()
    for v in variants:
        v = str(v).strip()
        if not v:
            continue
        key = _norm_name(v)
        if key and key not in seen:
            seen.add(key)
            cleaned.append(v)
    return cleaned

def _baseline_stem_core(stem):
    core = _norm_name(stem)
    for token in ["baselinemerge", "baseline", "merge"]:
        core = core.replace(token, "")
    return core

def resolve_baseline_path(region):
    """Fuzzy match region name to baseline shapefile."""
    baseline_dir = Path(r"Z:\DSAS\BaselineTemplate\Baselines")
    if not baseline_dir.exists():
        return None

    # Try exact match first.
    direct = baseline_dir / f"{region}_baseline.shp"
    if direct.exists():
        return direct

    # Accept any .shp containing baseline in stem (case-insensitive via normalization).
    baseline_files = [
        p for p in baseline_dir.glob("*.shp")
        if "baseline" in _norm_name(p.stem)
    ]
    if not baseline_files:
        return None

    region_vars = _region_variants(region)
    region_norms = [_norm_name(v) for v in region_vars]

    # First pass: contains/equality against cleaned baseline stem core.
    for bf in baseline_files:
        core = _baseline_stem_core(bf.stem)
        if any(rn == core or (rn and rn in core) or (core and core in rn) for rn in region_norms):
            return bf

    # Fallback: fuzzy score against both full stem and cleaned stem core.
    scored = []
    for bf in baseline_files:
        stem_norm = _norm_name(bf.stem)
        stem_core = _baseline_stem_core(bf.stem)
        score = max(
            max(_match_score(rn, stem_norm) for rn in region_norms),
            max(_match_score(rn, stem_core) for rn in region_norms),
        )
        scored.append((score, bf))

    if scored:
        best_score, best_path = max(scored, key=lambda item: item[0])
        if best_score >= 0.72:
            return best_path

    return None

baseline_rows = []
for row in valid_aoi.itertuples(index=False):
    try:
        aoi_gdf = gpd.read_file(row.aoi_path)
    except Exception as exc:
        # A bad or locked AOI file should not stop the other areas.
        log_run_row(
            "Cell 3 - AOI polygons and baselines",
            "AOI polygon could not be read",
            status="ERROR",
            region=row.region,
            aoi=row.aoi,
            detail=f"{row.aoi_path}: {exc}",
        )
        continue

    aoi_geom = aoi_gdf.union_all()

    baseline_path = resolve_baseline_path(row.region)
    if baseline_path is None:
        log_run_row(
            "Cell 3 - AOI polygons and baselines",
            "baseline shapefile not found for region",
            region=row.region,
            aoi=row.aoi,
        )
        continue

    baseline = gpd.read_file(baseline_path).to_crs(aoi_gdf.crs)
    baseline = baseline[baseline.intersects(aoi_geom)].copy()
    if baseline.empty:
        log_run_row(
            "Cell 3 - AOI polygons and baselines",
            "baseline does not overlap AOI polygon",
            region=row.region,
            aoi=row.aoi,
            detail=str(baseline_path),
        )
        continue

    baseline["region"] = row.region
    baseline["aoi"] = row.aoi
    baseline["aoi_path"] = row.aoi_path
    baseline["baseline_path"] = str(baseline_path)
    baseline_rows.append(baseline.to_crs(2193))

if len(baseline_rows) > 0:
    baseline = gpd.GeoDataFrame(pd.concat(baseline_rows, ignore_index=True), crs=2193)
else:
    print("WARNING: no baseline segments intersected any AOI polygon. Later steps will be skipped.")
    baseline = gpd.GeoDataFrame(
        {"region": [], "aoi": [], "aoi_path": [], "baseline_path": [], "geometry": []},
        geometry="geometry",
        crs=2193,
    )

# Find which AOIs have polygons but NO baseline overlap
baseline_aois_with_coverage = baseline[["region", "aoi"]].drop_duplicates()
all_valid_aois = valid_aoi[["region", "aoi"]].copy()
if all_valid_aois.empty:
    no_baseline_aois = all_valid_aois
else:
    no_baseline_mask = ~all_valid_aois.set_index(["region", "aoi"]).index.isin(
        baseline_aois_with_coverage.set_index(["region", "aoi"]).index
    )
    no_baseline_aois = all_valid_aois[no_baseline_mask].sort_values(["region", "aoi"]).reset_index(drop=True)

print("=" * 80)
print("TABLE 2: AOI POLYGONS FOUND BUT NO BASELINE OVERLAP (skipped, processing continues)")
print("=" * 80)
if not no_baseline_aois.empty:
    print(f"Total found but no baseline: {len(no_baseline_aois)} AOIs\n")
    display(no_baseline_aois)
else:
    print("None - all found AOIs have baseline coverage!\n")

================================================================================
TABLE 1: AOI POLYGONS NOT FOUND (skipped, processing continues for other areas)
================================================================================
None - all AOI polygons found!

================================================================================
TABLE 2: AOI POLYGONS FOUND BUT NO BASELINE OVERLAP (skipped, processing continues)
================================================================================
Total found but no baseline: 2 AOIs

     region                 aoi
0  Auckland     ManukapuaIsland
1  Auckland  TeHakono_clarksbay

time: 3.66 s (started: 2026-08-18 16:26:26 +12:00)

In [35]:
# 4) Use one AOI polygon as bbox geometry for preview
valid_aoi = aoi_index[aoi_index.aoi_exists].copy()

# Prefer an AOI that has baseline coverage so the preview is useful.
sample = None
preview_candidates = baseline[["region", "aoi"]].drop_duplicates() if len(baseline) else None
if preview_candidates is not None and len(preview_candidates) > 0:
    first = preview_candidates.iloc[0]
    match = valid_aoi[(valid_aoi.region == first.region) & (valid_aoi.aoi == first.aoi)]
    if len(match) > 0:
        sample = match.iloc[0]
if sample is None and len(valid_aoi) > 0:
    sample = valid_aoi.iloc[0]

m = None
if sample is None:
    print("Skipping preview: no AOI polygons available. See the run report for missing AOIs.")
else:
    bbox = gpd.read_file(sample.aoi_path).to_crs(2193)
    aoi_shoreline_paths = new_shorelines.query("region == @sample.region and aoi == @sample.aoi").shoreline_path

    shorelines_preview = []
    for fp in aoi_shoreline_paths:
        g = gpd.read_file(fp).to_crs(2193)
        g["source_file"] = fp
        shorelines_preview.append(g)

    if len(shorelines_preview) == 0:
        print(f"Skipping preview: no new shorelines for sample AOI {sample.region}/{sample.aoi}")
    else:
        shorelines_preview = gpd.GeoDataFrame(pd.concat(shorelines_preview, ignore_index=True), crs=2193)
        baseline_preview = baseline[(baseline.region == sample.region) & (baseline.aoi == sample.aoi)].copy()

        m = shorelines_preview.explore(name="new shorelines")
        bbox.boundary.explore(m=m, color="blue", name="AOI polygon (bbox)")
        if len(baseline_preview) > 0:
            baseline_preview.explore(m=m, color="red", name="baseline filtered to AOI")
        folium.LayerControl(collapsed=False).add_to(m)
m

time: 204 ms (started: 2026-08-18 16:26:30 +12:00)

In [ ]:
# 5) Generate transects per AOI using AOI-filtered baseline segments from Cell 3
# Make this cell self-contained for imports if run standalone.
import geopandas as gpd
import pandas as pd
import numpy as np
from pathlib import Path
from tqdm.auto import tqdm
from shapely.geometry import LineString, Point
from shapely import line_locate_point
import shapely
import zipfile
import folium

clear_run_rows("Cell 5 - transect generation")


def create_transects(line, spacing=10, transect_length=400):
    transects = []
    distances = np.arange(0, line.length, spacing)

    for distance in distances:
        point = line.interpolate(distance)
        nearest_point_ahead = line.interpolate(min(distance + 1e-6, line.length))
        direction = np.arctan2(nearest_point_ahead.y - point.y, nearest_point_ahead.x - point.x)
        transect = LineString([
            Point(
                point.x - transect_length / 2 * np.cos(direction + np.pi / 2),
                point.y - transect_length / 2 * np.sin(direction + np.pi / 2)
            ),
            Point(
                point.x + transect_length / 2 * np.cos(direction + np.pi / 2),
                point.y + transect_length / 2 * np.sin(direction + np.pi / 2)
            )
        ])
        transects.append(transect)
    return transects


# The DSAS notebook measures shoreline distances from each transect's LAST vertex, so that
# vertex must sit on the land side. create_transects puts the last vertex 90 degrees left of
# the baseline's digitisation direction, which is landward only when the baseline was drawn
# with land on its left -- enforce it here instead of trusting how each baseline was drawn.
LAND_POLY_ZIPS = [
    Path("lds-nz-coastlines-and-islands-polygons-topo-150k-GPKG.zip"),
    Path("Data for testing/lds-nz-coastlines-and-islands-polygons-topo-150k-GPKG.zip"),
]
ORIENT_PROBES_M = [30.0, 60.0, 120.0]


def load_land_polygons():
    for zpath in LAND_POLY_ZIPS:
        if not zpath.exists():
            continue
        with zipfile.ZipFile(zpath) as zf:
            inner = next(n for n in zf.namelist() if n.endswith(".gpkg"))
        return gpd.read_file(f"zip://{zpath}!/{inner}").to_crs(2193)
    raise FileNotFoundError(
        "LINZ land polygons not found. Download 'NZ Coastlines and Islands Polygons (Topo 1:50k)' "
        "from the LINZ Data Service as a GeoPackage and save "
        "lds-nz-coastlines-and-islands-polygons-topo-150k-GPKG.zip next to this notebook."
    )


land_polys = load_land_polygons()


def local_land_union(bounds, pad=3000):
    clip_box = shapely.box(bounds[0] - pad, bounds[1] - pad, bounds[2] + pad, bounds[3] + pad)
    candidates = land_polys.geometry.iloc[land_polys.sindex.query(clip_box, predicate="intersects")]
    if len(candidates) == 0:
        return None
    merged = shapely.union_all(shapely.intersection(candidates.values, clip_box))
    shapely.prepare(merged)
    return merged


def landwardness(points, land_union):
    """Positive = inside land (depth to the coast), negative = offshore (distance to the coast)."""
    pts = np.asarray(points, dtype=object)
    inside = shapely.contains(land_union, pts)
    dist = shapely.distance(pts, land_union.boundary)
    return np.where(inside, dist, -dist)


def orientation_vote(transect, land_union, anchor=None):
    """+1 when the transect's LAST vertex is its landward end, -1 when the first is, 0 undecided."""
    length = transect.length
    anchor = length / 2 if anchor is None else anchor
    score = 0.0
    for probe in ORIENT_PROBES_M:
        towards_first = transect.interpolate(max(anchor - probe, 0.0))
        towards_last = transect.interpolate(min(anchor + probe, length))
        lw = landwardness([towards_first, towards_last], land_union)
        score += (lw[1] - lw[0]) / probe
    return float(np.sign(score))


def orient_transects_landward(gdf, seg_ids):
    """Reverse transects whose last vertex is seaward.

    Votes are pooled per baseline segment: every transect from one baseline line shares the
    same land side by construction, so segment majority overrides noisy individual probes.
    """
    land_union = local_land_union(gdf.total_bounds)
    if land_union is None:
        return gdf, None
    votes = pd.Series([orientation_vote(t, land_union) for t in gdf.geometry], index=gdf.index)
    decisions = np.sign(votes.groupby(pd.Series(seg_ids, index=gdf.index)).transform("sum"))
    flip = decisions < 0
    gdf.loc[flip, "geometry"] = gdf.loc[flip, "geometry"].apply(lambda t: t.reverse())
    return gdf, {
        "reversed": int(flip.sum()),
        "kept": int((decisions > 0).sum()),
        "unresolved": int((decisions == 0).sum()),
    }


route_ids = {
    "NorthIsland": 100,
    "WaihekeIsland": 101,
    "MatakanaIsland": 102,
    "SouthIsland": 200,
    "JackettIsland": 201,
    "MoturoaRabbitIsland": 202,
    "Rakiura_StewartIsland": 203,
}


def _route_name_from_path(path_obj):
    stem = path_obj.stem
    if stem.lower().endswith("_route"):
        return stem[:-6]
    if stem.lower().endswith("route"):
        return stem[:-5].rstrip("_-")
    return stem


def load_routes_gdf():
    route_dirs = [
        Path(r"Z:\DSAS\BaselineTemplate\Routes"),
        Path("Data for testing/Routes"),
    ]

    route_frames = []
    for route_dir in route_dirs:
        if not route_dir.exists():
            continue

        for shp in route_dir.rglob("*.shp"):
            stem_norm = shp.stem.lower()
            if "route" not in stem_norm or "points" in stem_norm:
                continue

            g = gpd.read_file(shp)
            if g.empty:
                continue

            # Normalize route name so it always matches keys in route_ids.
            if "name" in g.columns and g["name"].notna().any():
                g["name"] = g["name"].fillna(_route_name_from_path(shp))
            else:
                g["name"] = _route_name_from_path(shp)

            route_frames.append(g.to_crs(2193))

    if len(route_frames) == 0:
        raise ValueError("No route shapefiles found. Check route paths.")

    return gpd.GeoDataFrame(pd.concat(route_frames, ignore_index=True), crs=2193)


existing_routes = globals().get("routes")
if existing_routes is None or len(existing_routes) == 0:
    routes = load_routes_gdf()
else:
    routes = existing_routes.to_crs(2193)

transect_frames = []
matched_routes = []

for _, row in tqdm(valid_aoi.iterrows(), total=len(valid_aoi)):
    region = row.region
    aoi = row.aoi
    aoi_geom = gpd.read_file(row.aoi_path).to_crs(2193).union_all()

    # Use baseline segments already filtered to this AOI in Cell 3.
    baseline_subset = baseline[(baseline.region == region) & (baseline.aoi == aoi)].copy()
    if len(baseline_subset) == 0:
        log_run_row("Cell 5 - transect generation", "no baseline segments for AOI", region=region, aoi=aoi)
        continue

    baseline_lines = baseline_subset.explode(index_parts=False).geometry
    baseline_lines = baseline_lines[baseline_lines.geom_type.isin(["LineString", "MultiLineString"])].explode(index_parts=False)
    if len(baseline_lines) == 0:
        log_run_row("Cell 5 - transect generation", "baseline has no line geometry", region=region, aoi=aoi)
        continue

    # Pick the best matching route by maximum overlap length with AOI.
    route_subset = routes[routes.intersects(aoi_geom)].copy()
    if len(route_subset) == 0:
        print(f"No route found for {region}/{aoi}")
        log_run_row("Cell 5 - transect generation", "no route intersects AOI", region=region, aoi=aoi)
        continue

    route_subset["overlap_len"] = route_subset.geometry.intersection(aoi_geom).length
    route = route_subset.sort_values("overlap_len", ascending=False).iloc[0]
    route_name = str(route["name"]).strip()
    if route_name not in route_ids:
        print(f"Route name '{route_name}' missing in route_ids for {region}/{aoi}")
        log_run_row(
            "Cell 5 - transect generation",
            "route name missing from route_ids",
            region=region,
            aoi=aoi,
            detail=route_name,
        )
        continue
    code = route_ids[route_name]

    aoi_transects = []
    baseline_seg_ids = []
    for seg_id, line in enumerate(baseline_lines):
        segment_transects = create_transects(line)
        aoi_transects.extend(segment_transects)
        baseline_seg_ids.extend([seg_id] * len(segment_transects))
    if len(aoi_transects) == 0:
        log_run_row("Cell 5 - transect generation", "no transects generated for AOI", region=region, aoi=aoi)
        continue

    aoi_transects = gpd.GeoDataFrame({
        "region": region,
        "aoi": aoi,
        "RouteName": route_name,
        "geometry": aoi_transects,
    }, crs=2193)

    aoi_transects, orient_summary = orient_transects_landward(aoi_transects, baseline_seg_ids)
    if orient_summary is None:
        log_run_row(
            "Cell 5 - transect generation",
            "no land polygons near AOI; transect orientation not checked",
            status="WARN",
            region=region,
            aoi=aoi,
        )
    else:
        if orient_summary["reversed"]:
            log_run_row(
                "Cell 5 - transect generation",
                "transects reversed so the last vertex is landward",
                status="ADJUSTED",
                region=region,
                aoi=aoi,
                detail=f"reversed={orient_summary['reversed']}; kept={orient_summary['kept']}",
            )
        if orient_summary["unresolved"]:
            log_run_row(
                "Cell 5 - transect generation",
                "transect orientation unresolved (left as generated)",
                status="WARN",
                region=region,
                aoi=aoi,
                detail=f"unresolved={orient_summary['unresolved']}",
            )

    meas = line_locate_point(route.geometry, aoi_transects.centroid)
    dist = (meas * 100).round().astype(int)
    aoi_transects["MEAS"] = meas
    aoi_transects["DIST"] = dist
    aoi_transects["Unique_ID"] = str(code) + aoi_transects["DIST"].astype(str).str.zfill(9)

    matched_routes.append({
        "region": region,
        "aoi": aoi,
        "route_name": route_name,
        "route_code": code,
        "transects": len(aoi_transects),
    })
    transect_frames.append(aoi_transects)


def _nudge_duplicates(gdf, group_keys, scope, shifts):
    for _, group in gdf.groupby(group_keys, sort=False):
        used = set()
        for idx in group.sort_values("DIST").index:
            dist = int(gdf.at[idx, "DIST"])
            shifted = 0
            while dist in used:
                dist += 1
                shifted += 1
            used.add(dist)
            if shifted:
                gdf.at[idx, "DIST"] = dist
                shifts.append({
                    "region": gdf.at[idx, "region"],
                    "aoi": gdf.at[idx, "aoi"],
                    "scope": scope,
                    "shift_cm": shifted,
                })


def enforce_unique_ids(gdf):
    # DIST is cm along the route, so baselines set well back from the route (harbour arms) can collapse onto one value.
    if len(gdf) == 0:
        return gdf, []

    gdf = gdf.sort_values(["RouteName", "region", "aoi", "MEAS"]).reset_index(drop=True)
    shifts = []

    # Resolve within each AOI first, so an AOI's IDs do not depend on which other areas were in the run.
    _nudge_duplicates(gdf, ["RouteName", "region", "aoi"], "within AOI", shifts)

    # Anything left is a genuine clash between AOIs sharing a route.
    _nudge_duplicates(gdf, ["RouteName"], "between AOIs on same route", shifts)

    gdf["Unique_ID"] = (
        gdf["RouteName"].map(route_ids).astype(str)
        + gdf["DIST"].astype(int).astype(str).str.zfill(9)
    )
    return gdf, shifts


matched_routes = pd.DataFrame(matched_routes, columns=["region", "aoi", "route_name", "route_code", "transects"])

if len(transect_frames) > 0:
    my_transects = gpd.GeoDataFrame(pd.concat(transect_frames, ignore_index=True), crs=2193)
    my_transects, dist_shifts = enforce_unique_ids(my_transects)
    if dist_shifts:
        shift_summary = (
            pd.DataFrame(dist_shifts)
            .groupby(["region", "aoi", "scope"])
            .agg(transects_adjusted=("shift_cm", "size"), max_shift_cm=("shift_cm", "max"))
            .reset_index()
        )
        for row in shift_summary.itertuples(index=False):
            log_run_row(
                "Cell 5 - transect generation",
                f"DIST nudged to keep Unique_ID unique ({row.scope})",
                status="ADJUSTED",
                region=row.region,
                aoi=row.aoi,
                detail=f"transects={row.transects_adjusted}; max_shift_cm={row.max_shift_cm}",
            )
        print(f"Adjusted {len(dist_shifts):,} DIST values (by 1 cm steps) so every Unique_ID is unique:")
        display(shift_summary)
else:
    print("WARNING: no transects generated for any AOI. See the run report for the reasons per area.")
    my_transects = gpd.GeoDataFrame(
        {"region": [], "aoi": [], "RouteName": [], "MEAS": [], "DIST": [], "Unique_ID": [], "geometry": []},
        geometry="geometry",
        crs=2193,
    )

display(matched_routes)
display(my_transects.head())

m = None
if len(my_transects) > 0:
    m = my_transects.explore(name="generated transects", color="orange")
    folium.LayerControl(collapsed=False).add_to(m)
m

Island code 

The first three numbers of the uniqueID indicates which island the point/rate/intersect is on.  

North Island 

Code 

South Island 

Code 

North Island 

100 

South Island 

200 

Waiheke Island 

101 

Jackett Island 

201 

Matakana Island 

102 

Moturoa Island 

202 

Rakiura Island 

203 


For each island I created a Route shapefile and determined the start point. The distance along the route tool was used to calculate the distance from the start of the route for each point along the route. 

The last 9 digits of the Unique_ID are made up of the route distance output (6 digits) (MEAS distance) and any necessary leading zeros.  

The output of the distance along the route tool (MEAS) is multiplied by 100, converted to an integer, and saved as ‘DIST’ to ensure each value is unique.  

MEAS 

DIST 

Code 

Unique_ID 

2050.2952311 

205029 

201 

201000205029

In [68]:
# QA 1: transect counts per Region/AOI
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

counts_by_aoi = (
    my_transects
    .groupby(["region", "aoi"])
    .size()
    .rename("transect_count")
    .reset_index()
    .sort_values(["region", "aoi"])
    .reset_index(drop=True)
)
counts_by_aoi

       region            aoi  transect_count
0    Auckland    Hobsonville              69
1    Auckland     Ngataringa              45
2    Auckland   OmokoritoBay             875
3    Auckland    OrongoPoint             205
4    Auckland   PollenIsland             173
5    Auckland    ShellyBeach             222
6    Auckland       ShoalBay             119
7    Auckland    SoldiersBay               8
8    Auckland        TeAtatu              55
9   Northland  FrenchmansBay             200
10  Northland          Pouto            2041
11  Northland        Tinopai             286

time: 0 ns (started: 2026-08-18 16:46:42 +12:00)

In [38]:
# QA 2: duplicate Unique_ID checks
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

dup_ids = my_transects[my_transects.duplicated("Unique_ID", keep=False)].sort_values("Unique_ID")
print(f"Duplicate Unique_ID rows: {len(dup_ids)}")

dup_ids[["region", "aoi", "RouteName", "Unique_ID"]].head(20)

Duplicate Unique_ID rows: 481

       region         aoi    RouteName     Unique_ID
75   Auckland  Ngataringa  NorthIsland  100217216882
73   Auckland  Ngataringa  NorthIsland  100217216882
72   Auckland  Ngataringa  NorthIsland  100217216882
71   Auckland  Ngataringa  NorthIsland  100217216882
70   Auckland  Ngataringa  NorthIsland  100217216882
69   Auckland  Ngataringa  NorthIsland  100217216882
76   Auckland  Ngataringa  NorthIsland  100217216882
77   Auckland  Ngataringa  NorthIsland  100217216882
74   Auckland  Ngataringa  NorthIsland  100217216882
79   Auckland  Ngataringa  NorthIsland  100217510654
80   Auckland  Ngataringa  NorthIsland  100217510654
103  Auckland  Ngataringa  NorthIsland  100217532053
104  Auckland  Ngataringa  NorthIsland  100217532053
105  Auckland  Ngataringa  NorthIsland  100217532053
106  Auckland  Ngataringa  NorthIsland  100217532053
107  Auckland  Ngataringa  NorthIsland  100217532053
111  Auckland  Ngataringa  NorthIsland  100217532834
110  Auckland  Ngataringa  NorthIsland  100217532834
88   Auckland  Ngataringa  NorthIsland  100217658659
87   Auckland  Ngataringa  NorthIsland  100217658659

time: 0 ns (started: 2026-08-18 16:27:08 +12:00)

In [39]:
# QA 3: route code prefix used in generated Unique_ID
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

prefix_counts = (
    my_transects
    .assign(prefix=my_transects.Unique_ID.astype(str).str[:3])
    .groupby(["region", "aoi", "RouteName", "prefix"])
    .size()
    .rename("count")
    .reset_index()
    .sort_values(["region", "aoi", "RouteName", "prefix"])
    .reset_index(drop=True)
)
prefix_counts

       region            aoi    RouteName prefix  count
0    Auckland    Hobsonville  NorthIsland    100     69
1    Auckland     Ngataringa  NorthIsland    100     45
2    Auckland   OmokoritoBay  NorthIsland    100    875
3    Auckland    OrongoPoint  NorthIsland    100    205
4    Auckland   PollenIsland  NorthIsland    100    173
5    Auckland    ShellyBeach  NorthIsland    100    222
6    Auckland       ShoalBay  NorthIsland    100    119
7    Auckland    SoldiersBay  NorthIsland    100      8
8    Auckland        TeAtatu  NorthIsland    100     55
9   Northland  FrenchmansBay  NorthIsland    100    200
10  Northland          Pouto  NorthIsland    100   2041
11  Northland        Tinopai  NorthIsland    100    286

time: 16 ms (started: 2026-08-18 16:27:08 +12:00)

In [40]:
# QA 4: confirm required fields exist
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

required_cols = ["region", "aoi", "RouteName", "MEAS", "DIST", "Unique_ID", "geometry"]
missing_cols = [c for c in required_cols if c not in my_transects.columns]
assert len(missing_cols) == 0, f"Missing required columns: {missing_cols}"
print("OK - all required columns are present")

OK - all required columns are present
time: 0 ns (started: 2026-08-18 16:27:08 +12:00)

In [41]:
# QA: MEAS distribution
my_transects.MEAS.describe()

count    4.298000e+03
mean     6.438449e+06
std      1.500471e+06
min      2.172169e+06
25%      6.423655e+06
50%      7.128570e+06
75%      7.248702e+06
max      7.258661e+06
Name: MEAS, dtype: float64

time: 15 ms (started: 2026-08-18 16:27:08 +12:00)

In [42]:
# QA: DIST distribution
my_transects.DIST.describe()

count    4.298000e+03
mean     6.438449e+08
std      1.500471e+08
min      2.172169e+08
25%      6.423655e+08
50%      7.128570e+08
75%      7.248702e+08
max      7.258661e+08
Name: DIST, dtype: float64

time: 0 ns (started: 2026-08-18 16:27:08 +12:00)

In [43]:
# QA: sample of generated IDs
my_transects.Unique_ID.astype(str).sort_values().head(20)

73     100217216882
74     100217216882
77     100217216882
72     100217216882
71     100217216882
70     100217216882
69     100217216882
75     100217216882
76     100217216882
79     100217510654
80     100217510654
78     100217511075
102    100217531811
103    100217532053
104    100217532053
106    100217532053
107    100217532053
105    100217532053
108    100217532232
109    100217532627
Name: Unique_ID, dtype: str

time: 0 ns (started: 2026-08-18 16:27:08 +12:00)

In [44]:
# QA: duplicates per AOI
if len(my_transects) == 0:
    dup_per_aoi = pd.DataFrame(columns=["region", "aoi", "duplicate_id_count"])
else:
    dup_per_aoi = (
        my_transects
        .groupby(["region", "aoi"])
        .apply(lambda g: g.Unique_ID.duplicated().sum())
        .rename("duplicate_id_count")
        .reset_index()
    )
dup_per_aoi

       region            aoi  duplicate_id_count
0    Auckland    Hobsonville                  22
1    Auckland     Ngataringa                  15
2    Auckland   OmokoritoBay                  17
3    Auckland    OrongoPoint                   6
4    Auckland   PollenIsland                  33
5    Auckland    ShellyBeach                  12
6    Auckland       ShoalBay                  13
7    Auckland    SoldiersBay                   0
8    Auckland        TeAtatu                  15
9   Northland  FrenchmansBay                   0
10  Northland          Pouto                 161
11  Northland        Tinopai                   0

time: 0 ns (started: 2026-08-18 16:27:08 +12:00)

In [67]:
# QA summary: PASS/FAIL checks for generated transects
qa_rows = []


def add_check(name, passed, detail=""):
    qa_rows.append({
        "check": name,
        "status": "PASS" if passed else "FAIL",
        "detail": str(detail),
    })


has_transects = "my_transects" in globals()
add_check("my_transects exists", has_transects, "Run Step 5 first" if not has_transects else f"rows={len(my_transects):,}")

if has_transects:
    add_check("non-empty transects", len(my_transects) > 0, f"rows={len(my_transects):,}")

    required_cols = ["region", "aoi", "RouteName", "MEAS", "DIST", "Unique_ID", "geometry"]
    missing_cols = [c for c in required_cols if c not in my_transects.columns]
    add_check("required columns present", len(missing_cols) == 0, "missing=" + ", ".join(missing_cols) if missing_cols else "all present")

    if len(missing_cols) == 0 and len(my_transects) > 0:
        null_geom = int(my_transects.geometry.isna().sum())
        add_check("geometry non-null", null_geom == 0, f"null_geometry={null_geom}")

        dup_uid = int(my_transects.duplicated("Unique_ID", keep=False).sum())
        add_check("no duplicate Unique_ID", dup_uid == 0, f"duplicate_rows={dup_uid}")

        dup_per_aoi = (
            my_transects
            .groupby(["region", "aoi"])
            .apply(lambda g: int(g.Unique_ID.duplicated().sum()))
            .rename("duplicate_id_count")
            .reset_index()
        )
        max_dup_per_aoi = int(dup_per_aoi["duplicate_id_count"].max()) if len(dup_per_aoi) > 0 else 0
        add_check("no duplicate Unique_ID within AOI", max_dup_per_aoi == 0, f"max_duplicate_per_aoi={max_dup_per_aoi}")

        meas_null = int(my_transects["MEAS"].isna().sum())
        dist_null = int(my_transects["DIST"].isna().sum())
        add_check("MEAS non-null", meas_null == 0, f"null_MEAS={meas_null}")
        add_check("DIST non-null", dist_null == 0, f"null_DIST={dist_null}")

        if dist_null == 0:
            dist_is_integer = bool((my_transects["DIST"] == my_transects["DIST"].round()).all())
            add_check("DIST integer-like", dist_is_integer, "all integer-like" if dist_is_integer else "non-integer DIST values found")

        uid_series = my_transects["Unique_ID"].astype(str)
        uid_format_ok = uid_series.str.match(r"^\d{12}$", na=False)
        bad_uid_count = int((~uid_format_ok).sum())
        add_check("Unique_ID format is 12 digits", bad_uid_count == 0, f"bad_format_rows={bad_uid_count}")

qa_summary = pd.DataFrame(qa_rows)

display(qa_summary)

fail_count = int((qa_summary["status"] == "FAIL").sum())
pass_count = int((qa_summary["status"] == "PASS").sum())
print(f"QA summary: {pass_count} PASS, {fail_count} FAIL")
if fail_count > 0:
    print("Review failed checks above.")
else:
    print("All QA checks passed.")

                               check status                   detail
0                my_transects exists   PASS               rows=4,298
1                non-empty transects   PASS               rows=4,298
2           required columns present   PASS              all present
3                  geometry non-null   PASS          null_geometry=0
4             no duplicate Unique_ID   PASS         duplicate_rows=0
5  no duplicate Unique_ID within AOI   PASS  max_duplicate_per_aoi=0
6                      MEAS non-null   PASS              null_MEAS=0
7                      DIST non-null   PASS              null_DIST=0
8                  DIST integer-like   PASS         all integer-like
9      Unique_ID format is 12 digits   PASS        bad_format_rows=0

QA summary: 10 PASS, 0 FAIL
All QA checks passed.
time: 15 ms (started: 2026-08-18 16:46:38 +12:00)

In [46]:
# Transect overview table
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"

my_transects[["region", "aoi", "RouteName", "Unique_ID", "MEAS", "DIST", "geometry"]].head(20)

,region,aoi,RouteName,Unique_ID,MEAS,DIST,geometry
0,Auckland,Hobsonville,NorthIsland,100228699268,2.286993e+06,228699268,"LINESTRING (1746851.631 5924586.71, 1746614.35..."
1,Auckland,Hobsonville,NorthIsland,100228698431,2.286984e+06,228698431,"LINESTRING (1746859.682 5924592.642, 1746622.4..."
2,Auckland,Hobsonville,NorthIsland,100228697640,2.286976e+06,228697640,"LINESTRING (1746867.733 5924598.574, 1746630.4..."
3,Auckland,Hobsonville,NorthIsland,100228696871,2.286969e+06,228696871,"LINESTRING (1746875.783 5924604.506, 1746638.5..."
4,Auckland,Hobsonville,NorthIsland,100228696096,2.286961e+06,228696096,"LINESTRING (1746883.834 5924610.438, 1746646.5..."
5,Auckland,Hobsonville,NorthIsland,100228695341,2.286953e+06,228695341,"LINESTRING (1746891.884 5924616.37, 1746654.60..."
6,Auckland,Hobsonville,NorthIsland,100228694483,2.286945e+06,228694483,"LINESTRING (1746899.957 5924622.318, 1746662.6..."
7,Auckland,Hobsonville,NorthIsland,100228693626,2.286936e+06,228693626,"LINESTRING (1746907.887 5924628.161, 1746670.8..."
8,Auckland,Hobsonville,NorthIsland,100228692912,2.286929e+06,228692912,"LINESTRING (1746916.058 5924634.182, 1746678.7..."
9,Auckland,Hobsonville,NorthIsland,100228692069,2.286921e+06,228692069,"LINESTRING (1746924.109 5924640.114, 1746686.7..."
10,Auckland,Hobsonville,NorthIsland,100228691226,2.286912e+06,228691226,"LINESTRING (1746932.159 5924646.046, 1746694.8..."
11,Auckland,Hobsonville,NorthIsland,100228690519,2.286905e+06,228690519,"LINESTRING (1746940.21 5924651.978, 1746702.88..."
12,Auckland,Hobsonville,NorthIsland,100228689687,2.286897e+06,228689687,"LINESTRING (1746948.26 5924657.91, 1746710.936..."
13,Auckland,Hobsonville,NorthIsland,100228688855,2.286889e+06,228688855,"LINESTRING (1746956.311 5924663.842, 1746718.9..."
14,Auckland,Hobsonville,NorthIsland,100228685755,2.286858e+06,228685755,"LINESTRING (1747039.896 5924773.552, 1746672.4..."
15,Auckland,Hobsonville,NorthIsland,100228684908,2.286849e+06,228684908,"LINESTRING (1747043.851 5924782.736, 1746676.4..."
16,Auckland,Hobsonville,NorthIsland,100228683913,2.286839e+06,228683913,"LINESTRING (1747047.835 5924791.989, 1746680.3..."
17,Auckland,Hobsonville,NorthIsland,100228682917,2.286829e+06,228682917,"LINESTRING (1747051.76 5924801.106, 1746684.36..."
18,Auckland,Hobsonville,NorthIsland,100228681922,2.286819e+06,228681922,"LINESTRING (1747055.715 5924810.291, 1746688.3..."
19,Auckland,Hobsonville,NorthIsland,100228680926,2.286809e+06,228680926,"LINESTRING (1747059.669 5924819.476, 1746692.2..."

time: 0 ns (started: 2026-08-18 16:27:08 +12:00)

In [69]:
output_dir = DATA_DIR
output_dir.mkdir(parents=True, exist_ok=True)
if len(my_transects) > 0:
    my_transects.to_file(output_dir / "new_transects.shp")
    print(f"Saved {len(my_transects):,} transects to {output_dir / 'new_transects.shp'}")
else:
    print("No transects to save - skipping shapefile export.")

Saved 4,298 transects to DataUpdatev2\catriona\new_transects.shp
time: 234 ms (started: 2026-08-18 16:46:46 +12:00)

In [51]:
# Map preview in the same AOI area used in Step 4
assert "my_transects" in globals(), "Run Step 5 first to create my_transects"
assert "baseline" in globals(), "Run Step 3 first to create baseline"
assert "new_shorelines" in globals(), "Run Step 1 first to create new_shorelines"

m = None
available_preview = my_transects[["region", "aoi"]].drop_duplicates().reset_index(drop=True)

if len(available_preview) == 0:
    print("Skipping map preview: no transects were generated. See the run report for skipped areas.")
else:
    sample_region = None
    sample_aoi = None
    if globals().get("sample") is not None:
        candidate = available_preview[
            (available_preview.region == sample.region) & (available_preview.aoi == sample.aoi)
        ]
        if len(candidate) > 0:
            sample_region = sample.region
            sample_aoi = sample.aoi
    if sample_region is None:
        sample_region = available_preview.iloc[0]["region"]
        sample_aoi = available_preview.iloc[0]["aoi"]

    transects_preview = my_transects[(my_transects.region == sample_region) & (my_transects.aoi == sample_aoi)].copy()

    if globals().get("sample") is not None and sample.region == sample_region and sample.aoi == sample_aoi and "bbox" in globals():
        bbox_preview = bbox.copy()
    else:
        aoi_path_preview = (
            valid_aoi
            .loc[(valid_aoi.region == sample_region) & (valid_aoi.aoi == sample_aoi), "aoi_path"]
            .iloc[0]
        )
        bbox_preview = gpd.read_file(aoi_path_preview).to_crs(2193)

    baseline_preview = baseline[(baseline.region == sample_region) & (baseline.aoi == sample_aoi)].copy()
    aoi_shoreline_paths = new_shorelines.query("region == @sample_region and aoi == @sample_aoi").shoreline_path

    shorelines_preview = []
    for fp in aoi_shoreline_paths:
        g = gpd.read_file(fp).to_crs(2193)
        shorelines_preview.append(g)

    m = transects_preview.explore(name="generated transects", color="orange")
    if len(shorelines_preview) > 0:
        gpd.GeoDataFrame(pd.concat(shorelines_preview, ignore_index=True), crs=2193).explore(m=m, name="new shorelines", color="black")
    bbox_preview.boundary.explore(m=m, color="blue", name="AOI polygon (bbox)")
    if len(baseline_preview) > 0:
        baseline_preview.explore(m=m, color="red", name="baseline filtered to AOI")
    folium.LayerControl(collapsed=False).add_to(m)
    print(f"Preview AOI: {sample_region}/{sample_aoi} | Transects shown: {len(transects_preview):,}")
m

Preview AOI: Auckland/Hobsonville | Transects shown: 69

time: 266 ms (started: 2026-08-18 16:27:10 +12:00)

In [79]:
# Run report: write every skipped/missing item and summary table to new_transects.csv
# Use the "cell" column to tab/filter the rows back to the step that produced them.
report_rows = list(run_report_rows)


def add_report_row(cell, category, status="OK", region=None, aoi=None, detail=""):
    report_rows.append({
        "cell": cell,
        "category": category,
        "status": status,
        "region": region,
        "aoi": aoi,
        "detail": str(detail),
    })


add_report_row("Cell 1 - shoreline search", "search settings", detail=f"{mode_label}; matches={len(new_shorelines)}")
for row in new_shorelines.itertuples(index=False):
    add_report_row(
        "Cell 1 - shoreline search",
        "shoreline file found",
        region=row.region,
        aoi=row.aoi,
        detail=f"{row.shoreline_path} (modified {row.modified})",
    )

for row in aoi_index.itertuples(index=False):
    add_report_row(
        "Cell 2 - AOI lookup",
        "AOI polygon resolved" if row.aoi_exists else "AOI polygon not found",
        status="OK" if row.aoi_exists else "MISSING",
        region=row.region,
        aoi=row.aoi,
        detail=row.aoi_path or "",
    )

if "matched_routes" in globals() and len(matched_routes) > 0:
    for row in matched_routes.itertuples(index=False):
        add_report_row(
            "Cell 5 - transect generation",
            "transects generated",
            region=row.region,
            aoi=row.aoi,
            detail=f"route={row.route_name} ({row.route_code}); transects={row.transects}",
        )

if "counts_by_aoi" in globals() and len(counts_by_aoi) > 0:
    for row in counts_by_aoi.itertuples(index=False):
        add_report_row(
            "QA 1 - transect counts",
            "transect count",
            region=row.region,
            aoi=row.aoi,
            detail=row.transect_count,
        )

if "qa_summary" in globals() and len(qa_summary) > 0:
    for row in qa_summary.itertuples(index=False):
        add_report_row("QA summary", row.check, status=row.status, detail=row.detail)

run_report = pd.DataFrame(report_rows, columns=["cell", "category", "status", "region", "aoi", "detail"])
RUN_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
run_report.to_csv(RUN_REPORT_PATH, index=False)

print(f"Run report saved to {RUN_REPORT_PATH} ({len(run_report)} rows)")
display(run_report.groupby(["cell", "status"]).size().rename("rows").reset_index())
display(run_report[~run_report.status.isin(["OK", "PASS"])])

Run report saved to DataUpdatev2\catriona\new_transects.csv (129 rows)

                                  cell    status  rows
0            Cell 1 - shoreline search        OK    68
1                  Cell 2 - AOI lookup        OK    14
2  Cell 3 - AOI polygons and baselines   MISSING     2
3         Cell 5 - transect generation  ADJUSTED     9
4         Cell 5 - transect generation   MISSING     2
5         Cell 5 - transect generation        OK    12
6               QA 1 - transect counts        OK    12
7                           QA summary      PASS    10

,cell,category,status,region,aoi,detail
0,Cell 3 - AOI polygons and baselines,baseline does not overlap AOI polygon,MISSING,Auckland,ManukapuaIsland,Z:\DSAS\BaselineTemplate\Baselines\Auckland_ba...
1,Cell 3 - AOI polygons and baselines,baseline does not overlap AOI polygon,MISSING,Auckland,TeHakono_clarksbay,Z:\DSAS\BaselineTemplate\Baselines\Auckland_ba...
2,Cell 5 - transect generation,no baseline segments for AOI,MISSING,Auckland,ManukapuaIsland,
3,Cell 5 - transect generation,no baseline segments for AOI,MISSING,Auckland,TeHakono_clarksbay,
4,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,Hobsonville,transects=22; max_shift_cm=9
5,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,Ngataringa,transects=15; max_shift_cm=8
6,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,OmokoritoBay,transects=17; max_shift_cm=4
7,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,OrongoPoint,transects=6; max_shift_cm=2
8,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,PollenIsland,transects=33; max_shift_cm=9
9,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,ShellyBeach,transects=12; max_shift_cm=3
10,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,ShoalBay,transects=13; max_shift_cm=2
11,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Auckland,TeAtatu,transects=15; max_shift_cm=3
12,Cell 5 - transect generation,DIST nudged to keep Unique_ID unique (within AOI),ADJUSTED,Northland,Pouto,transects=161; max_shift_cm=10

time: 16 ms (started: 2026-08-18 17:04:49 +12:00)